// Copyright (c) ZeroC, Inc.

namespace IceRpc.Slice;

/// <summary>Instructs the Slice Service source generator to implement <see cref="IDispatcher"/> by generating an
/// implementation of <see cref="IDispatcher.DispatchAsync"/> in the class on which this attribute is applied. Make sure
/// to mark your class as <see langword="partial"/> when you apply this attribute. Your class should also implement one
/// or more interface <c>I*Name*Service</c> (generated by the Slice compiler). The <c>DispatchAsync</c> produced by the
/// source generator dispatches to the appropriate method based on the operation name carried by the incoming request.
/// </summary>
/// <remarks>You must apply this attribute to any class for which you want the Slice Service source generator to
/// generate a <c>DispatchAsync</c> method. This attribute is not inherited by derived classes.</remarks>
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class SliceServiceAttribute : Attribute
{
}
