// Copyright (c) ZeroC, Inc.

using Google.Protobuf;
using IceRpc.Features;
using IceRpc.Protobuf.Internal;

namespace IceRpc.Protobuf;

/// <summary>Provides extension methods for <see cref="IncomingRequest" />.</summary>
/// <remarks>These methods are called by the <see cref="IDispatcher"/> implementation generated by the Protobuf service
/// generator.</remarks>
public static class IncomingRequestExtensions
{
    /// <summary>Dispatches a unary RPC method.</summary>
    /// <typeparam name="TInput">The type of the input message.</typeparam>
    /// <typeparam name="TOutput">The type of the output message.</typeparam>
    /// <typeparam name="TService">The generated INameService interface.</typeparam>
    /// <param name="request">The incoming request.</param>
    /// <param name="inputParser">A message parser used to decode the request payload.</param>
    /// <param name="service">The instance of <typeparamref name="TService"/> that implement the RPC.</param>
    /// <param name="method">The user-provided implementation of the RPC method.</param>
    /// <param name="cancellationToken">The cancellation token that accepts cancellation requests.</param>
    /// <returns>A value task that holds the outgoing response.</returns>
    public static async ValueTask<OutgoingResponse> DispatchUnaryAsync<TInput, TOutput, TService>(
        this IncomingRequest request,
        MessageParser<TInput> inputParser,
        TService service,
        Func<TService, TInput, IFeatureCollection, CancellationToken, ValueTask<TOutput>> method,
        CancellationToken cancellationToken) where TInput : IMessage<TInput>
                                             where TOutput : IMessage<TOutput>
                                             where TService : class
    {
        IProtobufFeature protobufFeature = request.Features.Get<IProtobufFeature>() ?? ProtobufFeature.Default;

        TInput input = await request.Payload.DecodeProtobufMessageAsync(
            inputParser,
            protobufFeature.MaxMessageLength,
            cancellationToken).ConfigureAwait(false);

        TOutput output = await method(service, input, request.Features, cancellationToken).ConfigureAwait(false);

        return new OutgoingResponse(request)
        {
            Payload = output.EncodeAsLengthPrefixedMessage(
                protobufFeature.EncodeOptions?.PipeOptions ?? ProtobufEncodeOptions.Default.PipeOptions)
        };
    }

    /// <summary>Dispatches a client-streaming RPC method.</summary>
    /// <typeparam name="TInput">The type of the input message.</typeparam>
    /// <typeparam name="TOutput">The type of the output message.</typeparam>
    /// <typeparam name="TService">The generated INameService interface.</typeparam>
    /// <param name="request">The incoming request.</param>
    /// <param name="inputParser">A message parser used to decode the request payload.</param>
    /// <param name="service">The instance of <typeparamref name="TService"/> that implement the RPC.</param>
    /// <param name="method">The user-provided implementation of the RPC method.</param>
    /// <param name="cancellationToken">The cancellation token that accepts cancellation requests.</param>
    /// <returns>A value task that holds the outgoing response.</returns>
    public static async ValueTask<OutgoingResponse> DispatchClientStreamingAsync<TInput, TOutput, TService>(
        this IncomingRequest request,
        MessageParser<TInput> inputParser,
        TService service,
        Func<TService, IAsyncEnumerable<TInput>, IFeatureCollection, CancellationToken, ValueTask<TOutput>> method,
        CancellationToken cancellationToken) where TInput : IMessage<TInput>
                                             where TOutput : IMessage<TOutput>
                                             where TService : class
    {
        IProtobufFeature protobufFeature = request.Features.Get<IProtobufFeature>() ?? ProtobufFeature.Default;

        IAsyncEnumerable<TInput> input = request.DetachPayload().ToAsyncEnumerable(
            inputParser,
            protobufFeature.MaxMessageLength,
            CancellationToken.None);

        TOutput output = await method(service, input, request.Features, cancellationToken).ConfigureAwait(false);

        return new OutgoingResponse(request)
        {
            Payload = output.EncodeAsLengthPrefixedMessage(
                protobufFeature.EncodeOptions?.PipeOptions ?? ProtobufEncodeOptions.Default.PipeOptions)
        };
    }

    /// <summary>Dispatches a server-streaming RPC method.</summary>
    /// <typeparam name="TInput">The type of the input message.</typeparam>
    /// <typeparam name="TOutput">The type of the output message.</typeparam>
    /// <typeparam name="TService">The generated INameService interface.</typeparam>
    /// <param name="request">The incoming request.</param>
    /// <param name="inputParser">A message parser used to decode the request payload.</param>
    /// <param name="service">The instance of <typeparamref name="TService"/> that implement the RPC.</param>
    /// <param name="method">The user-provided implementation of the RPC method.</param>
    /// <param name="cancellationToken">The cancellation token that accepts cancellation requests.</param>
    /// <returns>A value task that holds the outgoing response.</returns>
    public static async ValueTask<OutgoingResponse> DispatchServerStreamingAsync<TInput, TOutput, TService>(
        this IncomingRequest request,
        MessageParser<TInput> inputParser,
        TService service,
        Func<TService, TInput, IFeatureCollection, CancellationToken, ValueTask<IAsyncEnumerable<TOutput>>> method,
        CancellationToken cancellationToken) where TInput : IMessage<TInput>
                                             where TOutput : IMessage<TOutput>
                                             where TService : class
    {
        IProtobufFeature protobufFeature = request.Features.Get<IProtobufFeature>() ?? ProtobufFeature.Default;

        TInput input = await request.Payload.DecodeProtobufMessageAsync(
            inputParser,
            protobufFeature.MaxMessageLength,
            cancellationToken).ConfigureAwait(false);

        IAsyncEnumerable<TOutput> output = await method(service, input, request.Features, cancellationToken)
            .ConfigureAwait(false);

        return new OutgoingResponse(request)
        {
            PayloadContinuation = output.ToPipeReader(protobufFeature.EncodeOptions)
        };
    }

    /// <summary>Dispatches a bidi-streaming RPC method.</summary>
    /// <typeparam name="TInput">The type of the input message.</typeparam>
    /// <typeparam name="TOutput">The type of the output message.</typeparam>
    /// <typeparam name="TService">The generated INameService interface.</typeparam>
    /// <param name="request">The incoming request.</param>
    /// <param name="inputParser">A message parser used to decode the request payload.</param>
    /// <param name="service">The instance of <typeparamref name="TService"/> that implement the RPC.</param>
    /// <param name="method">The user-provided implementation of the RPC method.</param>
    /// <param name="cancellationToken">The cancellation token that accepts cancellation requests.</param>
    /// <returns>A value task that holds the outgoing response.</returns>
    public static async ValueTask<OutgoingResponse> DispatchBidiStreamingAsync<TInput, TOutput, TService>(
        this IncomingRequest request,
        MessageParser<TInput> inputParser,
        TService service,
        Func<TService, IAsyncEnumerable<TInput>, IFeatureCollection, CancellationToken, ValueTask<IAsyncEnumerable<TOutput>>> method,
        CancellationToken cancellationToken) where TInput : IMessage<TInput>
                                             where TOutput : IMessage<TOutput>
                                             where TService : class
    {
        IProtobufFeature protobufFeature = request.Features.Get<IProtobufFeature>() ?? ProtobufFeature.Default;

        IAsyncEnumerable<TInput> input = request.DetachPayload().ToAsyncEnumerable(
            inputParser,
            protobufFeature.MaxMessageLength,
            CancellationToken.None);

        IAsyncEnumerable<TOutput> output = await method(service, input, request.Features, cancellationToken)
            .ConfigureAwait(false);

        return new OutgoingResponse(request)
        {
            PayloadContinuation = output.ToPipeReader(protobufFeature.EncodeOptions)
        };
    }
}
