// Copyright (c) ZeroC, Inc.

namespace IceRpc.Ice.Codec;

/// <summary>Provides extension methods for <see cref="Type" />.</summary>
public static class TypeExtensions
{
    /// <summary>Retrieves the Ice type ID from a type with the attribute <see cref="IceTypeIdAttribute"/>.
    /// </summary>
    /// <param name="type">The type of a class or interface generated by the Ice compiler.</param>
    /// <returns>The Ice type ID, or <see langword="null" /> if <paramref name="type" /> does not carry the
    /// <see cref="IceTypeIdAttribute"/> attribute.
    /// </returns>
    public static string? GetIceTypeId(this Type type)
    {
        object[] attributes = type.GetCustomAttributes(typeof(IceTypeIdAttribute), false);
        return attributes.Length == 1 && attributes[0] is IceTypeIdAttribute typeId ? typeId.Value : null;
    }

    /// <summary>Retrieves the compact Ice type ID from a type with the attribute
    /// <see cref="CompactIceTypeIdAttribute"/>.</summary>
    /// <param name="type">The type of a class generated by the Ice compiler.</param>
    /// <returns>The compact Ice type ID, or <see langword="null" /> if <paramref name="type" /> does not carry the
    /// <see cref="CompactIceTypeIdAttribute"/> attribute.</returns>
    public static int? GetCompactIceTypeId(this Type type)
    {
        object[] attributes = type.GetCustomAttributes(typeof(CompactIceTypeIdAttribute), false);
        return attributes.Length == 1 && attributes[0] is CompactIceTypeIdAttribute typeId ? typeId.Value : null;
    }
}
