// Copyright (c) ZeroC, Inc.

using Google.Protobuf.WellKnownTypes;
using IceRpc;
using StreamExample;
using System.Security.Cryptography.X509Certificates;

// Load the test root CA certificate in order to connect to the server that uses a test server certificate.
using var rootCA = X509CertificateLoader.LoadCertificateFromFile("../../../../certs/cacert.der");

await using var connection = new ClientConnection(
    new Uri("icerpc://localhost"),
    clientAuthenticationOptions: CreateClientAuthenticationOptions(rootCA));

// GeneratorClient is a struct generated by protoc-gen-icerpc-csharp.
var generator = new GeneratorClient(connection);

IAsyncEnumerable<GenerateResponse> messages = await generator.GenerateNumbersAsync(new Empty());

uint count = 0;
await foreach (GenerateResponse message in messages)
{
    if (count == 10)
    {
        break;
    }
    else
    {
        Console.WriteLine($"Number #{count}: {message.Value}");
    }
    ++count;
}

await connection.ShutdownAsync();
