// Copyright (c) ZeroC, Inc.

using IceRpc;
using StreamExample;

await using var connection = new ClientConnection(new Uri("icerpc://localhost"));

// GeneratorProxy is a struct generated by the Slice compiler.
var generatorProxy = new GeneratorProxy(connection);

IAsyncEnumerable<int> numbers = await generatorProxy.GenerateNumbersAsync();

uint count = 0;
await foreach (int number in numbers)
{
    if (count == 10)
    {
        break;
    }
    else
    {
        Console.WriteLine($"Number #{count}: {number}");
    }
    ++count;
}

await connection.ShutdownAsync();
