// Copyright (c) ZeroC, Inc.

using IceRpc;
using StreamExample;
using System.Security.Cryptography.X509Certificates;

// Load the test root CA certificate in order to connect to the server that uses a test server certificate.
using X509Certificate2 rootCA = X509CertificateLoader.LoadCertificateFromFile("../../../../certs/cacert.der");

// Create a secure connection to the server using the default transport (QUIC).
await using var connection = new ClientConnection(
    new Uri("icerpc://localhost"),
    clientAuthenticationOptions: CreateClientAuthenticationOptions(rootCA));

// GeneratorProxy is a struct generated by the Slice compiler.
var generatorProxy = new GeneratorProxy(connection);

IAsyncEnumerable<int> numbers = await generatorProxy.GenerateNumbersAsync();

uint count = 0;
await foreach (int number in numbers)
{
    if (count == 10)
    {
        break;
    }
    else
    {
        Console.WriteLine($"Number #{count}: {number}");
    }
    ++count;
}

await connection.ShutdownAsync();
