// Copyright (c) ZeroC, Inc.

using System.Text;

namespace IceRpc.CaseConverter.Internal;

internal static class Converter
{
    /// <summary>Converts a name to Pascal case using the same algorithm as protoc's C# generator: an ASCII lowercase
    /// letter is capitalized at the start of the name or after any character other than a letter; digits are kept
    /// as-is; all other characters are dropped.</summary>
    /// <remarks>This method must produce the same output as protoc's <c>UnderscoresToCamelCase</c>: the build tasks
    /// use it to predict the name of the C# file that protoc generates.</remarks>
    internal static string ToProtocPascalCase(this string value) => Convert(value, preservePeriods: false);

    /// <summary>Converts a Protobuf package name into a C# namespace using the same algorithm as protoc's C#
    /// generator: periods are preserved and each period-separated segment is converted to Pascal case.</summary>
    /// <remarks>This method must produce the same output as protoc's <c>GetFileNamespace</c>: the code generated by
    /// protoc-gen-icerpc-csharp must use the same namespace as the code generated by protoc.</remarks>
    internal static string ToCsharpNamespace(this string package) => Convert(package, preservePeriods: true);

    private static string Convert(string value, bool preservePeriods)
    {
        var sb = new StringBuilder(value.Length);
        bool capitalizeNext = true;
        foreach (char c in value)
        {
            if (c is >= 'a' and <= 'z')
            {
                sb.Append(capitalizeNext ? (char)(c + ('A' - 'a')) : c);
                capitalizeNext = false;
            }
            else if (c is >= 'A' and <= 'Z')
            {
                sb.Append(c);
                capitalizeNext = false;
            }
            else if (c is >= '0' and <= '9')
            {
                sb.Append(c);
                capitalizeNext = true;
            }
            else
            {
                capitalizeNext = true;
                if (c == '.' && preservePeriods)
                {
                    sb.Append('.');
                }
            }
        }
        return sb.ToString();
    }
}
