// <auto-generated/>
// ZeroC.Slice.Generator version: '0.7.0-preview.1+b64a92e7aa2a6471ba5e391d00d28bf7de24ca6b'
// Generated from file: 'CodeGenerator.slice'

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

using ZeroC.Slice.Codec;

namespace ZeroC.Slice.Symbols.Compiler;

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::CodeGeneratorOption</c>.</remarks>
internal partial record struct CodeGeneratorOption
{
    internal required string Key { get; set; }

    internal required string Value { get; set; }

    /// <summary>Constructs a new instance of <see cref="CodeGeneratorOption" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal CodeGeneratorOption(
        string key,
        string value)
    {
        this.Key = key;
        this.Value = value;
    }

    /// <summary>Constructs a new instance of <see cref="CodeGeneratorOption" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal CodeGeneratorOption(ref SliceDecoder decoder)
    {
        this.Key = decoder.DecodeString();
        this.Value = decoder.DecodeString();
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.Key);
        encoder.EncodeString(this.Value);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::SliceFile</c>.</remarks>
internal partial record struct SliceFile
{
    internal required string Path { get; set; }

    internal Module ModuleDeclaration { get; set; }

    internal required global::System.Collections.Generic.IList<Attribute> Attributes { get; set; }

    internal required global::System.Collections.Generic.IList<Symbol> Contents { get; set; }

    /// <summary>Constructs a new instance of <see cref="SliceFile" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal SliceFile(
        string path,
        Module moduleDeclaration,
        global::System.Collections.Generic.IList<Attribute> attributes,
        global::System.Collections.Generic.IList<Symbol> contents)
    {
        this.Path = path;
        this.ModuleDeclaration = moduleDeclaration;
        this.Attributes = attributes;
        this.Contents = contents;
    }

    /// <summary>Constructs a new instance of <see cref="SliceFile" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal SliceFile(ref SliceDecoder decoder)
    {
        this.Path = decoder.DecodeString();
        this.ModuleDeclaration = new Module(ref decoder);
        this.Attributes = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Attribute(ref decoder));
        this.Contents = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => SymbolSliceDecoderExtensions.DecodeSymbol(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.Path);
        this.ModuleDeclaration.Encode(ref encoder);
        encoder.EncodeSequence(
            this.Attributes,
            (ref SliceEncoder encoder, Attribute value) => value.Encode(ref encoder));
        encoder.EncodeSequence(
            this.Contents,
            (ref SliceEncoder encoder, Symbol value) => SymbolSliceEncoderExtensions.EncodeSymbol(ref encoder, value));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::GeneratedFile</c>.</remarks>
internal partial record struct GeneratedFile
{
    internal required string Path { get; set; }

    internal required string Contents { get; set; }

    /// <summary>Constructs a new instance of <see cref="GeneratedFile" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal GeneratedFile(
        string path,
        string contents)
    {
        this.Path = path;
        this.Contents = contents;
    }

    /// <summary>Constructs a new instance of <see cref="GeneratedFile" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal GeneratedFile(ref SliceDecoder decoder)
    {
        this.Path = decoder.DecodeString();
        this.Contents = decoder.DecodeString();
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.Path);
        encoder.EncodeString(this.Contents);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this union from the Slice enum <c>Compiler::Symbol</c>.</remarks>
internal readonly partial union Symbol(Symbol.Interface, Symbol.BasicEnum, Symbol.VariantEnum, Symbol.Struct, Symbol.CustomType, Symbol.ResultType, Symbol.SequenceType, Symbol.DictionaryType, Symbol.TypeAlias) : global::System.IEquatable<Symbol>
{
    internal sealed partial record class Interface(global::ZeroC.Slice.Symbols.Compiler.Interface V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 0;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class BasicEnum(global::ZeroC.Slice.Symbols.Compiler.BasicEnum V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 1;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class VariantEnum(global::ZeroC.Slice.Symbols.Compiler.VariantEnum V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 2;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class Struct(global::ZeroC.Slice.Symbols.Compiler.Struct V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 3;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class CustomType(global::ZeroC.Slice.Symbols.Compiler.CustomType V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 4;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class ResultType(global::ZeroC.Slice.Symbols.Compiler.ResultType V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 5;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class SequenceType(global::ZeroC.Slice.Symbols.Compiler.SequenceType V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 6;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class DictionaryType(global::ZeroC.Slice.Symbols.Compiler.DictionaryType V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 7;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    internal sealed partial record class TypeAlias(global::ZeroC.Slice.Symbols.Compiler.TypeAlias V)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 8;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    /// <inheritdoc/>
    public bool Equals(Symbol other) => Equals(Value, other.Value);

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is Symbol other && Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode() => Value?.GetHashCode() ?? 0;

    /// <inheritdoc/>
    public override string ToString() => Value?.ToString() ?? "";

    /// <summary>Checks if two <see cref="Symbol" /> values are equal.</summary>
    /// <param name="left">The first value.</param>
    /// <param name="right">The second value.</param>
    /// <returns><see langword="true" /> if the values are equal; otherwise, <see langword="false" />.</returns>
    public static bool operator ==(Symbol left, Symbol right) => left.Equals(right);

    /// <summary>Checks if two <see cref="Symbol" /> values are not equal.</summary>
    /// <param name="left">The first value.</param>
    /// <param name="right">The second value.</param>
    /// <returns><see langword="true" /> if the values differ; otherwise, <see langword="false" />.</returns>
    public static bool operator !=(Symbol left, Symbol right) => !left.Equals(right);
}

/// <summary>Provides an extension method for encoding a <see cref="Symbol" /> using a <see cref="SliceEncoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::Symbol</c>.</remarks>
internal static class SymbolSliceEncoderExtensions
{
    /// <summary>Encodes a <see cref="Symbol" /> enum.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    /// <param name="value">The <see cref="Symbol" /> variant value to encode.</param>
    /// <exception cref="global::System.ArgumentException">Thrown when <paramref name="value" /> is the default value.</exception>
    internal static void EncodeSymbol(
        this ref SliceEncoder encoder,
        Symbol value)
    {
        switch (value)
        {
            case Symbol.Interface variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.BasicEnum variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.VariantEnum variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.Struct variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.CustomType variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.ResultType variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.SequenceType variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.DictionaryType variant:
                variant.Encode(ref encoder);
                break;
            case Symbol.TypeAlias variant:
                variant.Encode(ref encoder);
                break;
            case null:
                throw new global::System.ArgumentException("Cannot encode a default Symbol.", nameof(value));
        }
    }
}

/// <summary>Provides an extension method for decoding a <see cref="Symbol" /> using a <see cref="SliceDecoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::Symbol</c>.</remarks>
internal static class SymbolSliceDecoderExtensions
{
    /// <summary>Decodes a <see cref="Symbol" /> enum.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    /// <returns>The decoded <see cref="Symbol" /> variant value.</returns>
    internal static Symbol DecodeSymbol(this ref SliceDecoder decoder)
    {
        return decoder.DecodeVarInt32() switch
        {
            Symbol.Interface.Discriminant => DecodeInterface(ref decoder),
            Symbol.BasicEnum.Discriminant => DecodeBasicEnum(ref decoder),
            Symbol.VariantEnum.Discriminant => DecodeVariantEnum(ref decoder),
            Symbol.Struct.Discriminant => DecodeStruct(ref decoder),
            Symbol.CustomType.Discriminant => DecodeCustomType(ref decoder),
            Symbol.ResultType.Discriminant => DecodeResultType(ref decoder),
            Symbol.SequenceType.Discriminant => DecodeSequenceType(ref decoder),
            Symbol.DictionaryType.Discriminant => DecodeDictionaryType(ref decoder),
            Symbol.TypeAlias.Discriminant => DecodeTypeAlias(ref decoder),
            int value => throw new global::System.IO.InvalidDataException(
                $"Received invalid discriminant value '{value}' for Compiler::Symbol.")
        };

        static Symbol.Interface DecodeInterface(ref SliceDecoder decoder)
        {
            var result = new Symbol.Interface(V: new Interface(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.BasicEnum DecodeBasicEnum(ref SliceDecoder decoder)
        {
            var result = new Symbol.BasicEnum(V: new BasicEnum(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.VariantEnum DecodeVariantEnum(ref SliceDecoder decoder)
        {
            var result = new Symbol.VariantEnum(V: new VariantEnum(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.Struct DecodeStruct(ref SliceDecoder decoder)
        {
            var result = new Symbol.Struct(V: new Struct(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.CustomType DecodeCustomType(ref SliceDecoder decoder)
        {
            var result = new Symbol.CustomType(V: new CustomType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.ResultType DecodeResultType(ref SliceDecoder decoder)
        {
            var result = new Symbol.ResultType(V: new ResultType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.SequenceType DecodeSequenceType(ref SliceDecoder decoder)
        {
            var result = new Symbol.SequenceType(V: new SequenceType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.DictionaryType DecodeDictionaryType(ref SliceDecoder decoder)
        {
            var result = new Symbol.DictionaryType(V: new DictionaryType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.TypeAlias DecodeTypeAlias(ref SliceDecoder decoder)
        {
            var result = new Symbol.TypeAlias(V: new TypeAlias(ref decoder));
            decoder.SkipTagged();
            return result;
        }
    }
}
