// <auto-generated/>
// ZeroC.Slice.Generator version: '0.6.0-preview.1+5d01f5391d0f7a5877f83e590d9facbffbf7bf0e'
// Generated from file: 'CodeGenerator.slice'

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

using ZeroC.Slice.Codec;

namespace ZeroC.Slice.Symbols.Compiler;

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::SliceFile</c>.</remarks>
internal partial record struct SliceFile
{
    internal required string Path { get; set; }

    internal Module ModuleDeclaration { get; set; }

    internal required global::System.Collections.Generic.IList<Attribute> Attributes { get; set; }

    internal required global::System.Collections.Generic.IList<Symbol> Contents { get; set; }

    /// <summary>Constructs a new instance of <see cref="SliceFile" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal SliceFile(
        string path,
        Module moduleDeclaration,
        global::System.Collections.Generic.IList<Attribute> attributes,
        global::System.Collections.Generic.IList<Symbol> contents)
    {
        this.Path = path;
        this.ModuleDeclaration = moduleDeclaration;
        this.Attributes = attributes;
        this.Contents = contents;
    }

    /// <summary>Constructs a new instance of <see cref="SliceFile" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal SliceFile(ref SliceDecoder decoder)
    {
        this.Path = decoder.DecodeString();
        this.ModuleDeclaration = new Module(ref decoder);
        this.Attributes = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Attribute(ref decoder));
        this.Contents = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => SymbolSliceDecoderExtensions.DecodeSymbol(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.Path);
        this.ModuleDeclaration.Encode(ref encoder);
        encoder.EncodeSequence(
            this.Attributes,
            (ref SliceEncoder encoder, Attribute value) => value.Encode(ref encoder));
        encoder.EncodeSequence(
            this.Contents,
            (ref SliceEncoder encoder, Symbol value) => SymbolSliceEncoderExtensions.EncodeSymbol(ref encoder, value));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::GeneratedFile</c>.</remarks>
internal partial record struct GeneratedFile
{
    internal required string Path { get; set; }

    internal required string Contents { get; set; }

    /// <summary>Constructs a new instance of <see cref="GeneratedFile" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal GeneratedFile(
        string path,
        string contents)
    {
        this.Path = path;
        this.Contents = contents;
    }

    /// <summary>Constructs a new instance of <see cref="GeneratedFile" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal GeneratedFile(ref SliceDecoder decoder)
    {
        this.Path = decoder.DecodeString();
        this.Contents = decoder.DecodeString();
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.Path);
        encoder.EncodeString(this.Contents);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this discriminated union from the Slice enum <c>Compiler::Symbol</c>.</remarks>
[Dunet.Union]
internal abstract partial record class Symbol
{
    public partial record class Interface(global::ZeroC.Slice.Symbols.Compiler.Interface V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 0;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class BasicEnum(global::ZeroC.Slice.Symbols.Compiler.BasicEnum V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 1;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class VariantEnum(global::ZeroC.Slice.Symbols.Compiler.VariantEnum V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 2;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class Struct(global::ZeroC.Slice.Symbols.Compiler.Struct V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 3;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class CustomType(global::ZeroC.Slice.Symbols.Compiler.CustomType V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 4;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class SequenceType(global::ZeroC.Slice.Symbols.Compiler.SequenceType V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 5;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class DictionaryType(global::ZeroC.Slice.Symbols.Compiler.DictionaryType V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 6;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class ResultType(global::ZeroC.Slice.Symbols.Compiler.ResultType V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 7;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    public partial record class TypeAlias(global::ZeroC.Slice.Symbols.Compiler.TypeAlias V) : Symbol
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 8;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            this.V.Encode(ref encoder);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal abstract void Encode(ref SliceEncoder encoder);
}

/// <summary>Provides an extension method for encoding a <see cref="Symbol" /> using a <see cref="SliceEncoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::Symbol</c>.</remarks>
internal static class SymbolSliceEncoderExtensions
{
    /// <summary>Encodes a <see cref="Symbol" /> enum.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    /// <param name="value">The <see cref="Symbol" /> variant value to encode.</param>
    internal static void EncodeSymbol(
        this ref SliceEncoder encoder,
        Symbol value) =>
            value.Encode(ref encoder);
}

/// <summary>Provides an extension method for decoding a <see cref="Symbol" /> using a <see cref="SliceDecoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::Symbol</c>.</remarks>
internal static class SymbolSliceDecoderExtensions
{
    /// <summary>Decodes a <see cref="Symbol" /> enum.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    /// <returns>The decoded <see cref="Symbol" /> variant value.</returns>
    internal static Symbol DecodeSymbol(this ref SliceDecoder decoder)
    {
        return decoder.DecodeVarInt32() switch
        {
            Symbol.Interface.Discriminant => DecodeInterface(ref decoder),
            Symbol.BasicEnum.Discriminant => DecodeBasicEnum(ref decoder),
            Symbol.VariantEnum.Discriminant => DecodeVariantEnum(ref decoder),
            Symbol.Struct.Discriminant => DecodeStruct(ref decoder),
            Symbol.CustomType.Discriminant => DecodeCustomType(ref decoder),
            Symbol.SequenceType.Discriminant => DecodeSequenceType(ref decoder),
            Symbol.DictionaryType.Discriminant => DecodeDictionaryType(ref decoder),
            Symbol.ResultType.Discriminant => DecodeResultType(ref decoder),
            Symbol.TypeAlias.Discriminant => DecodeTypeAlias(ref decoder),
            int value => throw new global::System.IO.InvalidDataException(
                $"Received invalid discriminant value '{value}' for Symbol.")
        };

        static Symbol.Interface DecodeInterface(ref SliceDecoder decoder)
        {
            var result = new Symbol.Interface(V: new Interface(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.BasicEnum DecodeBasicEnum(ref SliceDecoder decoder)
        {
            var result = new Symbol.BasicEnum(V: new BasicEnum(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.VariantEnum DecodeVariantEnum(ref SliceDecoder decoder)
        {
            var result = new Symbol.VariantEnum(V: new VariantEnum(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.Struct DecodeStruct(ref SliceDecoder decoder)
        {
            var result = new Symbol.Struct(V: new Struct(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.CustomType DecodeCustomType(ref SliceDecoder decoder)
        {
            var result = new Symbol.CustomType(V: new CustomType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.SequenceType DecodeSequenceType(ref SliceDecoder decoder)
        {
            var result = new Symbol.SequenceType(V: new SequenceType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.DictionaryType DecodeDictionaryType(ref SliceDecoder decoder)
        {
            var result = new Symbol.DictionaryType(V: new DictionaryType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.ResultType DecodeResultType(ref SliceDecoder decoder)
        {
            var result = new Symbol.ResultType(V: new ResultType(ref decoder));
            decoder.SkipTagged();
            return result;
        }

        static Symbol.TypeAlias DecodeTypeAlias(ref SliceDecoder decoder)
        {
            var result = new Symbol.TypeAlias(V: new TypeAlias(ref decoder));
            decoder.SkipTagged();
            return result;
        }
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Diagnostic</c>.</remarks>
internal partial record struct Diagnostic
{
    internal DiagnosticLevel Level { get; set; }

    internal required string Message { get; set; }

    internal string? Source { get; set; }

    /// <summary>Constructs a new instance of <see cref="Diagnostic" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Diagnostic(
        DiagnosticLevel level,
        string message,
        string? source)
    {
        this.Level = level;
        this.Message = message;
        this.Source = source;
    }

    /// <summary>Constructs a new instance of <see cref="Diagnostic" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Diagnostic(ref SliceDecoder decoder)
    {
        var bitSequenceReader = decoder.GetBitSequenceReader(1);
        this.Level = DiagnosticLevelSliceDecoderExtensions.DecodeDiagnosticLevel(ref decoder);
        this.Message = decoder.DecodeString();
        this.Source = bitSequenceReader.Read() ? decoder.DecodeString() : null;
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        var bitSequenceWriter = encoder.GetBitSequenceWriter(1);
        DiagnosticLevelSliceEncoderExtensions.EncodeDiagnosticLevel(ref encoder, this.Level);
        encoder.EncodeString(this.Message);
        bitSequenceWriter.Write(this.Source != null);
        if (this.Source != null)
        {
            encoder.EncodeString(this.Source);
        }
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this enum from the Slice enum <c>Compiler::DiagnosticLevel</c>.</remarks>
internal enum DiagnosticLevel : byte
{
    Info = 0,

    Warning = 1,

    Error = 2,
}

/// <summary>Provides an extension method for creating a <see cref="DiagnosticLevel" /> from a <see langword="byte" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::DiagnosticLevel</c>.</remarks>
internal static class DiagnosticLevelByteExtensions
{
    /// <summary>Converts a <see langword="byte" /> into the corresponding <see cref="DiagnosticLevel" /> enumerator.</summary>
    /// <param name="value">The value being converted.</param>
    /// <returns>The enumerator.</returns>
    internal static DiagnosticLevel AsDiagnosticLevel(this byte value) =>
        (DiagnosticLevel)value;
}

/// <summary>Provides an extension method for encoding a <see cref="DiagnosticLevel" /> using a <see cref="SliceEncoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::DiagnosticLevel</c>.</remarks>
internal static class DiagnosticLevelSliceEncoderExtensions
{
    /// <summary>Encodes a <see cref="DiagnosticLevel" /> enum.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    /// <param name="value">The <see cref="DiagnosticLevel" /> enumerator value to encode.</param>
    internal static void EncodeDiagnosticLevel(
        this ref SliceEncoder encoder,
        DiagnosticLevel value) =>
            encoder.EncodeUInt8((byte)value);
}

/// <summary>Provides an extension method for decoding a <see cref="DiagnosticLevel" /> using a <see cref="SliceDecoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::DiagnosticLevel</c>.</remarks>
internal static class DiagnosticLevelSliceDecoderExtensions
{
    /// <summary>Decodes a <see cref="DiagnosticLevel" /> enum.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    /// <returns>The decoded <see cref="DiagnosticLevel" /> enumerator value.</returns>
    internal static DiagnosticLevel DecodeDiagnosticLevel(this ref SliceDecoder decoder) =>
        DiagnosticLevelByteExtensions.AsDiagnosticLevel(decoder.DecodeUInt8());
}
