// <auto-generated/>
// ZeroC.Slice.Generator version: '0.7.0-preview.1+49b74394282746fbb92aeedb3f80107fbc5ed4ff'
// Generated from file: 'Diagnostics.slice'

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

using ZeroC.Slice.Codec;

namespace ZeroC.Slice.Symbols.Compiler;

/// <summary>A message that is reported to provide information and context for errors, warnings, or other issues.</summary>
/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Diagnostic</c>.</remarks>
internal partial record struct Diagnostic
{
    /// <summary>The exact kind of diagnostic.</summary>
    internal required DiagnosticKind Kind { get; set; }

    /// <summary>The fully-scoped Slice identifier of the element that this diagnostic is in reference to (if there is one).</summary>
    internal string? Source { get; set; }

    /// <summary>Any additional information that should be reported alongside this diagnostic&apos;s main message.</summary>
    internal required global::System.Collections.Generic.IList<DiagnosticNote> Notes { get; set; }

    /// <summary>Constructs a new instance of <see cref="Diagnostic" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Diagnostic(
        DiagnosticKind kind,
        string? source,
        global::System.Collections.Generic.IList<DiagnosticNote> notes)
    {
        this.Kind = kind;
        this.Source = source;
        this.Notes = notes;
    }

    /// <summary>Constructs a new instance of <see cref="Diagnostic" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Diagnostic(ref SliceDecoder decoder)
    {
        var bitSequenceReader = decoder.GetBitSequenceReader(1);
        this.Kind = DiagnosticKindSliceDecoderExtensions.DecodeDiagnosticKind(ref decoder);
        this.Source = bitSequenceReader.Read() ? decoder.DecodeString() : null;
        this.Notes = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new DiagnosticNote(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        var bitSequenceWriter = encoder.GetBitSequenceWriter(1);
        DiagnosticKindSliceEncoderExtensions.EncodeDiagnosticKind(ref encoder, this.Kind);
        bitSequenceWriter.Write(this.Source != null);
        if (this.Source != null)
        {
            encoder.EncodeString(this.Source!);
        }
        encoder.EncodeSequence(
            this.Notes,
            (ref SliceEncoder encoder, DiagnosticNote value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <summary>Stores additional information to report alongside a <see cref="Diagnostic" />.</summary>
/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::DiagnosticNote</c>.</remarks>
internal partial record struct DiagnosticNote
{
    /// <summary>The message to emit alongside the main diagnostic which this note is attached to.</summary>
    internal required string Message { get; set; }

    /// <summary>The fully-scoped Slice identifier of the element that this note is in reference to (if there is one).</summary>
    internal string? Source { get; set; }

    /// <summary>Constructs a new instance of <see cref="DiagnosticNote" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal DiagnosticNote(
        string message,
        string? source)
    {
        this.Message = message;
        this.Source = source;
    }

    /// <summary>Constructs a new instance of <see cref="DiagnosticNote" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal DiagnosticNote(ref SliceDecoder decoder)
    {
        var bitSequenceReader = decoder.GetBitSequenceReader(1);
        this.Message = decoder.DecodeString();
        this.Source = bitSequenceReader.Read() ? decoder.DecodeString() : null;
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        var bitSequenceWriter = encoder.GetBitSequenceWriter(1);
        encoder.EncodeString(this.Message);
        bitSequenceWriter.Write(this.Source != null);
        if (this.Source != null)
        {
            encoder.EncodeString(this.Source!);
        }
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this union from the Slice enum <c>Compiler::DiagnosticKind</c>.</remarks>
internal partial union DiagnosticKind(DiagnosticKind.Info, DiagnosticKind.Warning, DiagnosticKind.Error, DiagnosticKind.InvalidAttribute, DiagnosticKind.UnknownAttribute, DiagnosticKind.MissingRequiredAttribute, DiagnosticKind.AttributeIsNotRepeatable, DiagnosticKind.InvalidAttributeArgument, DiagnosticKind.IncorrectAttributeArgumentCount, DiagnosticKind.Unknown) : global::System.IEquatable<DiagnosticKind>
{
    /// <summary>A general purpose diagnostic which is purely informational.</summary>
    internal sealed partial record class Info(string Message)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 0;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Message);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>A general purpose diagnostic which should be emitted as a warning.</summary>
    internal sealed partial record class Warning(string Message)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 1;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Message);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>A general purpose diagnostic which should be emitted as an error.</summary>
    internal sealed partial record class Error(string Message)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 2;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Message);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>
    /// An attribute was applied to a Slice element for which it&apos;s invalid.
    /// For example: applying `[oneway]` to a struct (&apos;oneway&apos; is only allowed on operations).
    /// </summary>
    /// <param name="Directive">the directive of the invalid attribute.</param>
    internal sealed partial record class InvalidAttribute(string Directive)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 3;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Directive);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>
    /// An unknown attribute was encountered, which uses a known prefix.
    /// For example: if a C# code-generator encountered the following attribute: `[cs::foobar]`.
    /// </summary>
    /// <param name="Directive">the directive of the unknown attribute.</param>
    internal sealed partial record class UnknownAttribute(string Directive)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 4;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Directive);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>
    /// An element requires a specific attribute to be applied to it, which is not present.
    /// For example: custom types must have their mapped type specified with a `[xxx:type(...)]` attribute.
    /// </summary>
    /// <param name="ExpectedAttribute">the missing attribute; should include placeholder names for expected arguments.</param>
    internal sealed partial record class MissingRequiredAttribute(string ExpectedAttribute)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 5;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.ExpectedAttribute);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>
    /// A non-repeatable attribute was applied to the same element multiple times.
    /// For example: `[compress(Args)] [compress(Return)] myOperation()`; &apos;compress&apos; is not repeatable.
    /// </summary>
    /// <param name="Directive">the directive of the non-repeatable attribute.</param>
    internal sealed partial record class AttributeIsNotRepeatable(string Directive)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 6;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Directive);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>
    /// An invalid argument was provided to an attribute which otherwise accepts arguments.
    /// For example: `[compress(FooBar)] myOperation()`; &apos;compress&apos; accepts arguments but &apos;FooBar&apos; is not a valid one.
    /// </summary>
    /// <param name="Directive">the directive of the attribute.</param>
    /// <param name="Argument">the invalid argument that was provided.</param>
    internal sealed partial record class InvalidAttributeArgument(string Directive, string Argument)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 7;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Directive);
            encoder.EncodeString(this.Argument);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>
    /// Too few or too many arguments were supplied to an otherwise valid attribute.
    /// For example: `[oneway(FooBar)]` (&apos;oneway&apos; takes no arguments) or `[compress]` (&apos;compress&apos; requires arguments).
    /// </summary>
    /// <param name="Directive">the directive of the attribute.</param>
    /// <param name="MinExpected">the minimum number of arguments this attribute can be given.</param>
    /// <param name="MaxExpected">the maximum number of arguments this attribute can be given.</param>
    /// <param name="ActualCount">the number of arguments this attribute was actually given.</param>
    internal sealed partial record class IncorrectAttributeArgumentCount(string Directive, byte MinExpected, byte MaxExpected, byte ActualCount)
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        internal const int Discriminant = 8;

        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            var sizePlaceholder = encoder.GetPlaceholderSpan(4);
            int startPos = encoder.EncodedByteCount;
            encoder.EncodeString(this.Directive);
            encoder.EncodeUInt8(this.MinExpected);
            encoder.EncodeUInt8(this.MaxExpected);
            encoder.EncodeUInt8(this.ActualCount);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
            SliceEncoder.EncodeVarUInt62((ulong)(encoder.EncodedByteCount - startPos), sizePlaceholder);
        }
    }

    /// <summary>Represents a variant not defined in the local Slice definition of unchecked enum 'DiagnosticKind'.</summary>
    /// <param name="Discriminant">The discriminant of this unknown variant.</param>
    /// <param name="Fields">The encoded fields of this unknown variant.</param>
    internal sealed partial record class Unknown(int Discriminant, global::System.ReadOnlyMemory<byte> Fields)
    {
        /// <summary>Encodes this variant with a Slice encoder.</summary>
        /// <param name="encoder">The Slice encoder.</param>
        internal void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            encoder.EncodeSize(Fields.Length);
            encoder.WriteByteSpan(Fields.Span);
        }
    }

    /// <inheritdoc/>
    public bool Equals(DiagnosticKind other) => Equals(Value, other.Value);

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is DiagnosticKind other && Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode() => Value?.GetHashCode() ?? 0;

    /// <inheritdoc/>
    public override string ToString() => Value?.ToString() ?? "";

    /// <summary>Checks if two <see cref="DiagnosticKind" /> values are equal.</summary>
    /// <param name="left">The first value.</param>
    /// <param name="right">The second value.</param>
    /// <returns><see langword="true" /> if the values are equal; otherwise, <see langword="false" />.</returns>
    public static bool operator ==(DiagnosticKind left, DiagnosticKind right) => left.Equals(right);

    /// <summary>Checks if two <see cref="DiagnosticKind" /> values are not equal.</summary>
    /// <param name="left">The first value.</param>
    /// <param name="right">The second value.</param>
    /// <returns><see langword="true" /> if the values differ; otherwise, <see langword="false" />.</returns>
    public static bool operator !=(DiagnosticKind left, DiagnosticKind right) => !left.Equals(right);
}

/// <summary>Provides an extension method for encoding a <see cref="DiagnosticKind" /> using a <see cref="SliceEncoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::DiagnosticKind</c>.</remarks>
internal static class DiagnosticKindSliceEncoderExtensions
{
    /// <summary>Encodes a <see cref="DiagnosticKind" /> enum.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    /// <param name="value">The <see cref="DiagnosticKind" /> variant value to encode.</param>
    internal static void EncodeDiagnosticKind(
        this ref SliceEncoder encoder,
        DiagnosticKind value)
    {
        switch (value)
        {
            case DiagnosticKind.Info variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.Warning variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.Error variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.InvalidAttribute variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.UnknownAttribute variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.MissingRequiredAttribute variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.AttributeIsNotRepeatable variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.InvalidAttributeArgument variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.IncorrectAttributeArgumentCount variant:
                variant.Encode(ref encoder);
                break;
            case DiagnosticKind.Unknown variant:
                variant.Encode(ref encoder);
                break;
            case null:
                throw new global::System.InvalidOperationException("Cannot encode a default DiagnosticKind.");
        }
    }
}

/// <summary>Provides an extension method for decoding a <see cref="DiagnosticKind" /> using a <see cref="SliceDecoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::DiagnosticKind</c>.</remarks>
internal static class DiagnosticKindSliceDecoderExtensions
{
    /// <summary>Decodes a <see cref="DiagnosticKind" /> enum.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    /// <returns>The decoded <see cref="DiagnosticKind" /> variant value.</returns>
    internal static DiagnosticKind DecodeDiagnosticKind(this ref SliceDecoder decoder)
    {
        return decoder.DecodeVarInt32() switch
        {
            DiagnosticKind.Info.Discriminant => DecodeInfo(ref decoder),
            DiagnosticKind.Warning.Discriminant => DecodeWarning(ref decoder),
            DiagnosticKind.Error.Discriminant => DecodeError(ref decoder),
            DiagnosticKind.InvalidAttribute.Discriminant => DecodeInvalidAttribute(ref decoder),
            DiagnosticKind.UnknownAttribute.Discriminant => DecodeUnknownAttribute(ref decoder),
            DiagnosticKind.MissingRequiredAttribute.Discriminant => DecodeMissingRequiredAttribute(ref decoder),
            DiagnosticKind.AttributeIsNotRepeatable.Discriminant => DecodeAttributeIsNotRepeatable(ref decoder),
            DiagnosticKind.InvalidAttributeArgument.Discriminant => DecodeInvalidAttributeArgument(ref decoder),
            DiagnosticKind.IncorrectAttributeArgumentCount.Discriminant => DecodeIncorrectAttributeArgumentCount(ref decoder),
            int value => new DiagnosticKind.Unknown(value, decoder.DecodeSequence<byte>())
        };

        static DiagnosticKind.Info DecodeInfo(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.Info(Message: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.Warning DecodeWarning(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.Warning(Message: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.Error DecodeError(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.Error(Message: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.InvalidAttribute DecodeInvalidAttribute(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.InvalidAttribute(Directive: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.UnknownAttribute DecodeUnknownAttribute(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.UnknownAttribute(Directive: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.MissingRequiredAttribute DecodeMissingRequiredAttribute(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.MissingRequiredAttribute(ExpectedAttribute: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.AttributeIsNotRepeatable DecodeAttributeIsNotRepeatable(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.AttributeIsNotRepeatable(Directive: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.InvalidAttributeArgument DecodeInvalidAttributeArgument(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.InvalidAttributeArgument(
                Directive: decoder.DecodeString(),
                Argument: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static DiagnosticKind.IncorrectAttributeArgumentCount DecodeIncorrectAttributeArgumentCount(ref SliceDecoder decoder)
        {
            decoder.SkipSize();
            var result = new DiagnosticKind.IncorrectAttributeArgumentCount(
                Directive: decoder.DecodeString(),
                MinExpected: decoder.DecodeUInt8(),
                MaxExpected: decoder.DecodeUInt8(),
                ActualCount: decoder.DecodeUInt8());
            decoder.SkipTagged();
            return result;
        }
    }
}
