// <auto-generated/>
// ZeroC.Slice.Generator version: '0.6.0-preview.1+2a196a7c25c7c2ac7112f32a2281c82bc49e8be6'
// Generated from file: 'DocComment.slice'

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

using ZeroC.Slice.Codec;

namespace ZeroC.Slice.Symbols.Compiler;

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::DocComment</c>.</remarks>
internal partial record struct DocComment
{
    internal required global::System.Collections.Generic.IList<MessageComponent> Overview { get; set; }

    internal required global::System.Collections.Generic.IList<string> SeeTags { get; set; }

    /// <summary>Constructs a new instance of <see cref="DocComment" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal DocComment(
        global::System.Collections.Generic.IList<MessageComponent> overview,
        global::System.Collections.Generic.IList<string> seeTags)
    {
        this.Overview = overview;
        this.SeeTags = seeTags;
    }

    /// <summary>Constructs a new instance of <see cref="DocComment" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal DocComment(ref SliceDecoder decoder)
    {
        this.Overview = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => MessageComponentSliceDecoderExtensions.DecodeMessageComponent(ref decoder));
        this.SeeTags = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => decoder.DecodeString());
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeSequence(
            this.Overview,
            (ref SliceEncoder encoder, MessageComponent value) => MessageComponentSliceEncoderExtensions.EncodeMessageComponent(ref encoder, value));
        encoder.EncodeSequence(
            this.SeeTags,
            (ref SliceEncoder encoder, string value) => encoder.EncodeString(value));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this discriminated union from the Slice enum <c>Compiler::MessageComponent</c>.</remarks>
[Dunet.Union]
internal abstract partial record class MessageComponent
{
    partial record class Text(string V) : MessageComponent
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 0;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            encoder.EncodeString(this.V);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    partial record class Link(string V) : MessageComponent
    {
        /// <summary>The discriminant of this variant, used for encoding/decoding.</summary>
        public const int Discriminant = 1;

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal override void Encode(ref SliceEncoder encoder)
        {
            encoder.EncodeVarInt32(Discriminant);
            encoder.EncodeString(this.V);
            encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
        }
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal abstract void Encode(ref SliceEncoder encoder);
}

/// <summary>Provides an extension method for encoding a <see cref="MessageComponent" /> using a <see cref="SliceEncoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::MessageComponent</c>.</remarks>
internal static class MessageComponentSliceEncoderExtensions
{
    /// <summary>Encodes a <see cref="MessageComponent" /> enum.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    /// <param name="value">The <see cref="MessageComponent" /> variant value to encode.</param>
    internal static void EncodeMessageComponent(
        this ref SliceEncoder encoder,
        MessageComponent value) =>
            value.Encode(ref encoder);
}

/// <summary>Provides an extension method for decoding a <see cref="MessageComponent" /> using a <see cref="SliceDecoder" />.</summary>
/// <remarks>The Slice compiler generated this static class from the Slice enum <c>Compiler::MessageComponent</c>.</remarks>
internal static class MessageComponentSliceDecoderExtensions
{
    /// <summary>Decodes a <see cref="MessageComponent" /> enum.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    /// <returns>The decoded <see cref="MessageComponent" /> variant value.</returns>
    internal static MessageComponent DecodeMessageComponent(this ref SliceDecoder decoder)
    {
        return decoder.DecodeVarInt32() switch
        {
            MessageComponent.Text.Discriminant => DecodeText(ref decoder),
            MessageComponent.Link.Discriminant => DecodeLink(ref decoder),
            int value => throw new global::System.IO.InvalidDataException(
                $"Received invalid discriminant value '{value}' for Compiler::MessageComponent.")
        };

        static MessageComponent.Text DecodeText(ref SliceDecoder decoder)
        {
            var result = new MessageComponent.Text(V: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }

        static MessageComponent.Link DecodeLink(ref SliceDecoder decoder)
        {
            var result = new MessageComponent.Link(V: decoder.DecodeString());
            decoder.SkipTagged();
            return result;
        }
    }
}
