// <auto-generated/>
// ZeroC.Slice.Generator version: '0.6.0-preview.1+f91c9792ec352724c5df4fac4359c112a4bba137'
// Generated from file: 'SyntaxElements.slice'

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

using ZeroC.Slice.Codec;

namespace ZeroC.Slice.Symbols.Compiler;

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Attribute</c>.</remarks>
internal partial record struct Attribute
{
    internal required string Directive { get; set; }

    internal required global::System.Collections.Generic.IList<string> Args { get; set; }

    /// <summary>Constructs a new instance of <see cref="Attribute" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Attribute(
        string directive,
        global::System.Collections.Generic.IList<string> args)
    {
        this.Directive = directive;
        this.Args = args;
    }

    /// <summary>Constructs a new instance of <see cref="Attribute" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Attribute(ref SliceDecoder decoder)
    {
        this.Directive = decoder.DecodeString();
        this.Args = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => decoder.DecodeString());
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.Directive);
        encoder.EncodeSequence(
            this.Args,
            (ref SliceEncoder encoder, string value) => encoder.EncodeString(value));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::TypeRef</c>.</remarks>
internal partial record struct TypeRef
{
    internal required string TypeId { get; set; }

    internal bool IsOptional { get; set; }

    internal required global::System.Collections.Generic.IList<Attribute> TypeAttributes { get; set; }

    /// <summary>Constructs a new instance of <see cref="TypeRef" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal TypeRef(
        string typeId,
        bool isOptional,
        global::System.Collections.Generic.IList<Attribute> typeAttributes)
    {
        this.TypeId = typeId;
        this.IsOptional = isOptional;
        this.TypeAttributes = typeAttributes;
    }

    /// <summary>Constructs a new instance of <see cref="TypeRef" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal TypeRef(ref SliceDecoder decoder)
    {
        this.TypeId = decoder.DecodeString();
        this.IsOptional = decoder.DecodeBool();
        this.TypeAttributes = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Attribute(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.TypeId);
        encoder.EncodeBool(this.IsOptional);
        encoder.EncodeSequence(
            this.TypeAttributes,
            (ref SliceEncoder encoder, Attribute value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::EntityInfo</c>.</remarks>
internal partial record struct EntityInfo
{
    internal required string Identifier { get; set; }

    internal required global::System.Collections.Generic.IList<Attribute> Attributes { get; set; }

    internal DocComment? Comment { get; set; }

    /// <summary>Constructs a new instance of <see cref="EntityInfo" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal EntityInfo(
        string identifier,
        global::System.Collections.Generic.IList<Attribute> attributes,
        DocComment? comment)
    {
        this.Identifier = identifier;
        this.Attributes = attributes;
        this.Comment = comment;
    }

    /// <summary>Constructs a new instance of <see cref="EntityInfo" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal EntityInfo(ref SliceDecoder decoder)
    {
        var bitSequenceReader = decoder.GetBitSequenceReader(1);
        this.Identifier = decoder.DecodeString();
        this.Attributes = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Attribute(ref decoder));
        this.Comment = bitSequenceReader.Read() ? (DocComment?)new DocComment(ref decoder) : null;
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        var bitSequenceWriter = encoder.GetBitSequenceWriter(1);
        encoder.EncodeString(this.Identifier);
        encoder.EncodeSequence(
            this.Attributes,
            (ref SliceEncoder encoder, Attribute value) => value.Encode(ref encoder));
        bitSequenceWriter.Write(this.Comment != null);
        if (this.Comment != null)
        {
            this.Comment.Value.Encode(ref encoder);
        }
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Module</c>.</remarks>
internal partial record struct Module
{
    internal required string Identifier { get; set; }

    internal required global::System.Collections.Generic.IList<Attribute> Attributes { get; set; }

    /// <summary>Constructs a new instance of <see cref="Module" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Module(
        string identifier,
        global::System.Collections.Generic.IList<Attribute> attributes)
    {
        this.Identifier = identifier;
        this.Attributes = attributes;
    }

    /// <summary>Constructs a new instance of <see cref="Module" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Module(ref SliceDecoder decoder)
    {
        this.Identifier = decoder.DecodeString();
        this.Attributes = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Attribute(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeString(this.Identifier);
        encoder.EncodeSequence(
            this.Attributes,
            (ref SliceEncoder encoder, Attribute value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Struct</c>.</remarks>
internal partial record struct Struct
{
    internal EntityInfo EntityInfo { get; set; }

    internal bool IsCompact { get; set; }

    internal required global::System.Collections.Generic.IList<Field> Fields { get; set; }

    /// <summary>Constructs a new instance of <see cref="Struct" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Struct(
        EntityInfo entityInfo,
        bool isCompact,
        global::System.Collections.Generic.IList<Field> fields)
    {
        this.EntityInfo = entityInfo;
        this.IsCompact = isCompact;
        this.Fields = fields;
    }

    /// <summary>Constructs a new instance of <see cref="Struct" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Struct(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.IsCompact = decoder.DecodeBool();
        this.Fields = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Field(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeBool(this.IsCompact);
        encoder.EncodeSequence(
            this.Fields,
            (ref SliceEncoder encoder, Field value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Field</c>.</remarks>
internal partial record struct Field
{
    internal EntityInfo EntityInfo { get; set; }

    internal int? Tag { get; set; }

    internal TypeRef DataType { get; set; }

    /// <summary>Constructs a new instance of <see cref="Field" />.</summary>
    internal Field(
        EntityInfo entityInfo,
        int? tag,
        TypeRef dataType)
    {
        this.EntityInfo = entityInfo;
        this.Tag = tag;
        this.DataType = dataType;
    }

    /// <summary>Constructs a new instance of <see cref="Field" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    internal Field(ref SliceDecoder decoder)
    {
        var bitSequenceReader = decoder.GetBitSequenceReader(1);
        this.EntityInfo = new EntityInfo(ref decoder);
        this.Tag = bitSequenceReader.Read() ? (int?)decoder.DecodeVarInt32() : null;
        this.DataType = new TypeRef(ref decoder);
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        var bitSequenceWriter = encoder.GetBitSequenceWriter(1);
        this.EntityInfo.Encode(ref encoder);
        bitSequenceWriter.Write(this.Tag != null);
        if (this.Tag != null)
        {
            encoder.EncodeVarInt32(this.Tag.Value);
        }
        this.DataType.Encode(ref encoder);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Interface</c>.</remarks>
internal partial record struct Interface
{
    internal EntityInfo EntityInfo { get; set; }

    internal required global::System.Collections.Generic.IList<string> Bases { get; set; }

    internal required global::System.Collections.Generic.IList<Operation> Operations { get; set; }

    /// <summary>Constructs a new instance of <see cref="Interface" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Interface(
        EntityInfo entityInfo,
        global::System.Collections.Generic.IList<string> bases,
        global::System.Collections.Generic.IList<Operation> operations)
    {
        this.EntityInfo = entityInfo;
        this.Bases = bases;
        this.Operations = operations;
    }

    /// <summary>Constructs a new instance of <see cref="Interface" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Interface(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.Bases = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => decoder.DecodeString());
        this.Operations = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Operation(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeSequence(
            this.Bases,
            (ref SliceEncoder encoder, string value) => encoder.EncodeString(value));
        encoder.EncodeSequence(
            this.Operations,
            (ref SliceEncoder encoder, Operation value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Operation</c>.</remarks>
internal partial record struct Operation
{
    internal EntityInfo EntityInfo { get; set; }

    internal bool IsIdempotent { get; set; }

    internal required global::System.Collections.Generic.IList<Field> Parameters { get; set; }

    internal bool HasStreamedParameter { get; set; }

    internal required global::System.Collections.Generic.IList<Field> ReturnType { get; set; }

    internal bool HasStreamedReturn { get; set; }

    /// <summary>Constructs a new instance of <see cref="Operation" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Operation(
        EntityInfo entityInfo,
        bool isIdempotent,
        global::System.Collections.Generic.IList<Field> parameters,
        bool hasStreamedParameter,
        global::System.Collections.Generic.IList<Field> returnType,
        bool hasStreamedReturn)
    {
        this.EntityInfo = entityInfo;
        this.IsIdempotent = isIdempotent;
        this.Parameters = parameters;
        this.HasStreamedParameter = hasStreamedParameter;
        this.ReturnType = returnType;
        this.HasStreamedReturn = hasStreamedReturn;
    }

    /// <summary>Constructs a new instance of <see cref="Operation" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Operation(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.IsIdempotent = decoder.DecodeBool();
        this.Parameters = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Field(ref decoder));
        this.HasStreamedParameter = decoder.DecodeBool();
        this.ReturnType = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Field(ref decoder));
        this.HasStreamedReturn = decoder.DecodeBool();
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeBool(this.IsIdempotent);
        encoder.EncodeSequence(
            this.Parameters,
            (ref SliceEncoder encoder, Field value) => value.Encode(ref encoder));
        encoder.EncodeBool(this.HasStreamedParameter);
        encoder.EncodeSequence(
            this.ReturnType,
            (ref SliceEncoder encoder, Field value) => value.Encode(ref encoder));
        encoder.EncodeBool(this.HasStreamedReturn);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::BasicEnum</c>.</remarks>
internal partial record struct BasicEnum
{
    internal EntityInfo EntityInfo { get; set; }

    internal bool IsUnchecked { get; set; }

    internal required string Underlying { get; set; }

    internal required global::System.Collections.Generic.IList<Enumerator> Enumerators { get; set; }

    /// <summary>Constructs a new instance of <see cref="BasicEnum" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal BasicEnum(
        EntityInfo entityInfo,
        bool isUnchecked,
        string underlying,
        global::System.Collections.Generic.IList<Enumerator> enumerators)
    {
        this.EntityInfo = entityInfo;
        this.IsUnchecked = isUnchecked;
        this.Underlying = underlying;
        this.Enumerators = enumerators;
    }

    /// <summary>Constructs a new instance of <see cref="BasicEnum" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal BasicEnum(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.IsUnchecked = decoder.DecodeBool();
        this.Underlying = decoder.DecodeString();
        this.Enumerators = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Enumerator(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeBool(this.IsUnchecked);
        encoder.EncodeString(this.Underlying);
        encoder.EncodeSequence(
            this.Enumerators,
            (ref SliceEncoder encoder, Enumerator value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Enumerator</c>.</remarks>
internal partial record struct Enumerator
{
    internal EntityInfo EntityInfo { get; set; }

    internal ulong AbsoluteValue { get; set; }

    internal bool HasNegativeValue { get; set; }

    /// <summary>Constructs a new instance of <see cref="Enumerator" />.</summary>
    internal Enumerator(
        EntityInfo entityInfo,
        ulong absoluteValue,
        bool hasNegativeValue)
    {
        this.EntityInfo = entityInfo;
        this.AbsoluteValue = absoluteValue;
        this.HasNegativeValue = hasNegativeValue;
    }

    /// <summary>Constructs a new instance of <see cref="Enumerator" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    internal Enumerator(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.AbsoluteValue = decoder.DecodeUInt64();
        this.HasNegativeValue = decoder.DecodeBool();
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeUInt64(this.AbsoluteValue);
        encoder.EncodeBool(this.HasNegativeValue);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::VariantEnum</c>.</remarks>
internal partial record struct VariantEnum
{
    internal EntityInfo EntityInfo { get; set; }

    internal bool IsCompact { get; set; }

    internal bool IsUnchecked { get; set; }

    internal required global::System.Collections.Generic.IList<Variant> Variants { get; set; }

    /// <summary>Constructs a new instance of <see cref="VariantEnum" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal VariantEnum(
        EntityInfo entityInfo,
        bool isCompact,
        bool isUnchecked,
        global::System.Collections.Generic.IList<Variant> variants)
    {
        this.EntityInfo = entityInfo;
        this.IsCompact = isCompact;
        this.IsUnchecked = isUnchecked;
        this.Variants = variants;
    }

    /// <summary>Constructs a new instance of <see cref="VariantEnum" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal VariantEnum(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.IsCompact = decoder.DecodeBool();
        this.IsUnchecked = decoder.DecodeBool();
        this.Variants = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Variant(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeBool(this.IsCompact);
        encoder.EncodeBool(this.IsUnchecked);
        encoder.EncodeSequence(
            this.Variants,
            (ref SliceEncoder encoder, Variant value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::Variant</c>.</remarks>
internal partial record struct Variant
{
    internal EntityInfo EntityInfo { get; set; }

    internal int Discriminant { get; set; }

    internal required global::System.Collections.Generic.IList<Field> Fields { get; set; }

    /// <summary>Constructs a new instance of <see cref="Variant" />.</summary>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Variant(
        EntityInfo entityInfo,
        int discriminant,
        global::System.Collections.Generic.IList<Field> fields)
    {
        this.EntityInfo = entityInfo;
        this.Discriminant = discriminant;
        this.Fields = fields;
    }

    /// <summary>Constructs a new instance of <see cref="Variant" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    internal Variant(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.Discriminant = decoder.DecodeInt32();
        this.Fields = decoder.DecodeSequence(
            (ref SliceDecoder decoder) => new Field(ref decoder));
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeInt32(this.Discriminant);
        encoder.EncodeSequence(
            this.Fields,
            (ref SliceEncoder encoder, Field value) => value.Encode(ref encoder));
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::CustomType</c>.</remarks>
internal partial record struct CustomType
{
    internal EntityInfo EntityInfo { get; set; }

    /// <summary>Constructs a new instance of <see cref="CustomType" />.</summary>
    internal CustomType(EntityInfo entityInfo)
    {
        this.EntityInfo = entityInfo;
    }

    /// <summary>Constructs a new instance of <see cref="CustomType" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    internal CustomType(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::TypeAlias</c>.</remarks>
internal partial record struct TypeAlias
{
    internal EntityInfo EntityInfo { get; set; }

    internal TypeRef UnderlyingType { get; set; }

    /// <summary>Constructs a new instance of <see cref="TypeAlias" />.</summary>
    internal TypeAlias(
        EntityInfo entityInfo,
        TypeRef underlyingType)
    {
        this.EntityInfo = entityInfo;
        this.UnderlyingType = underlyingType;
    }

    /// <summary>Constructs a new instance of <see cref="TypeAlias" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    internal TypeAlias(ref SliceDecoder decoder)
    {
        this.EntityInfo = new EntityInfo(ref decoder);
        this.UnderlyingType = new TypeRef(ref decoder);
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.EntityInfo.Encode(ref encoder);
        this.UnderlyingType.Encode(ref encoder);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::SequenceType</c>.</remarks>
internal partial record struct SequenceType
{
    internal TypeRef ElementType { get; set; }

    /// <summary>Constructs a new instance of <see cref="SequenceType" />.</summary>
    internal SequenceType(TypeRef elementType)
    {
        this.ElementType = elementType;
    }

    /// <summary>Constructs a new instance of <see cref="SequenceType" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    internal SequenceType(ref SliceDecoder decoder)
    {
        this.ElementType = new TypeRef(ref decoder);
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.ElementType.Encode(ref encoder);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::DictionaryType</c>.</remarks>
internal partial record struct DictionaryType
{
    internal TypeRef KeyType { get; set; }

    internal TypeRef ValueType { get; set; }

    /// <summary>Constructs a new instance of <see cref="DictionaryType" />.</summary>
    internal DictionaryType(
        TypeRef keyType,
        TypeRef valueType)
    {
        this.KeyType = keyType;
        this.ValueType = valueType;
    }

    /// <summary>Constructs a new instance of <see cref="DictionaryType" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    internal DictionaryType(ref SliceDecoder decoder)
    {
        this.KeyType = new TypeRef(ref decoder);
        this.ValueType = new TypeRef(ref decoder);
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.KeyType.Encode(ref encoder);
        this.ValueType.Encode(ref encoder);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}

/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Compiler::ResultType</c>.</remarks>
internal partial record struct ResultType
{
    internal TypeRef SuccessType { get; set; }

    internal TypeRef FailureType { get; set; }

    /// <summary>Constructs a new instance of <see cref="ResultType" />.</summary>
    internal ResultType(
        TypeRef successType,
        TypeRef failureType)
    {
        this.SuccessType = successType;
        this.FailureType = failureType;
    }

    /// <summary>Constructs a new instance of <see cref="ResultType" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    internal ResultType(ref SliceDecoder decoder)
    {
        this.SuccessType = new TypeRef(ref decoder);
        this.FailureType = new TypeRef(ref decoder);
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    internal readonly void Encode(ref SliceEncoder encoder)
    {
        this.SuccessType.Encode(ref encoder);
        this.FailureType.Encode(ref encoder);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}
