// Copyright (c) ZeroC, Inc.

using IceRpc;

// Protobuf module visitor_center in greeter.proto maps to C# namespace VisitorCenter.
using VisitorCenter;

await using var connection = new ClientConnection(new Uri("icerpc://localhost"));

// GreeterClient is a struct generated by the IceRpc protobuf plug-in.
var client = new GreeterClient(connection);
var request = new GreetRequest();
request.Name = Environment.UserName;

GreetResponse response = await client.GreetAsync(request);

Console.WriteLine(response.Greeting);

await connection.ShutdownAsync();
