// Copyright (c) ZeroC, Inc.

using ZeroC.CodeBuilder;

namespace IceRpc.ServiceGenerator.Internal;

internal class Emitter
{
    internal string Emit(ServiceClass serviceClass, CancellationToken cancellationToken)
    {
        // Stop if we're asked to.
        cancellationToken.ThrowIfCancellationRequested();

        CodeBlock codeBlock = Preamble();
        foreach (Idl idl in serviceClass.ServiceMethods.Select(serviceMethod => serviceMethod.Idl).Distinct())
        {
            codeBlock.WriteLine($"using IceRpc.{idl};");
        }
        codeBlock.WriteLine("using ZeroC.Slice.Codec;");

        if (serviceClass.ContainingNamespace is not null)
        {
            codeBlock.AddBlock($"namespace {serviceClass.ContainingNamespace};");
        }

        // We need to implement IDispatcher all the time, even when there is a base class that itself implements
        // IDispatcher.
        CodeBlock container = new ContainerBuilder($"partial {serviceClass.Keyword}", serviceClass.Name)
            .AddBase("IceRpc.IDispatcher")
            .AddComment(
                "summary",
                @"Implements <see cref=""IceRpc.IDispatcher"" /> for the generated interface(s) implemented by this class.")
            .AddBlock(GenerateDispatch(serviceClass))
            .Build();

        ContainerDefinition? containerDefinition = serviceClass;
        while (containerDefinition.Enclosing is ContainerDefinition enclosing)
        {
            container = new ContainerBuilder($"partial {enclosing.Keyword}", enclosing.Name)
                .AddBlock(container)
                .Build();

            containerDefinition = enclosing;
        }

        codeBlock.AddBlock(container);
        return codeBlock.ToString().ReplaceLineEndings();
    }

    private static CodeBlock GenerateDispatch(ServiceClass serviceClass)
    {
        string methodModifier = serviceClass.HasBaseServiceClass
            ? "public override"
            : serviceClass.IsSealed ? "public" : "public virtual";

        return @$"
/// <summary>Dispatches an incoming request to a method of <see cref=""{serviceClass.Name}"" /> based on
/// the operation name carried by the request.</summary>
/// <param name=""request"">The incoming request.</param>
/// <param name=""cancellationToken"">A cancellation token that receives the cancellation requests.</param>
/// <returns>The outgoing response.</returns>
{methodModifier} global::System.Threading.Tasks.ValueTask<IceRpc.OutgoingResponse> DispatchAsync(
    IceRpc.IncomingRequest request,
    global::System.Threading.CancellationToken cancellationToken)
{{
    {GenerateDispatchBody(serviceClass).Indent()}
}}
";
    }

    private static CodeBlock GenerateDispatchBody(ServiceClass serviceClass)
    {
        if (serviceClass.ServiceMethods.Count > 0)
        {
            var cases = new CodeBlock();
            foreach (IServiceMethod serviceMethod in serviceClass.ServiceMethods)
            {
                // The Indent is intentional: we want to indent the code in the case body.
                cases.AddBlock(GenerateDispatchCase(serviceMethod).Indent());
            }
            cases = cases.Indent(); // This indents all the case statements in the switch.

            var fallback = new CodeBlock(
                serviceClass.HasBaseServiceClass ?
                    @"default:
    return base.DispatchAsync(request, cancellationToken);" :
                    @"default:
    return new(new IceRpc.OutgoingResponse(request, IceRpc.StatusCode.NotImplemented));").Indent();

            return @$"switch (request.Operation)
{{
    {cases}

    {fallback}
}}";
        }
        else
        {
            return serviceClass.HasBaseServiceClass ?
                "return base.DispatchAsync(request, cancellationToken);" :
                "return new(new IceRpc.OutgoingResponse(request, IceRpc.StatusCode.NotImplemented));";
        }
    }

    private static CodeBlock GenerateDispatchCase(IServiceMethod serviceMethod) =>
        @$"case ""{serviceMethod.OperationName}"":
{serviceMethod.GenerateDispatchCaseBody()}";

    private static CodeBlock Preamble() => @$"
// <auto-generated/>
// IceRpc.ServiceGenerator version: {typeof(ServiceGenerator).Assembly.GetName().Version!.ToString(3)}

#nullable enable

#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

";
}
