// Copyright (c) ZeroC, Inc.

using IceRpc;
using IceRpc.Slice;

namespace Microsoft.Extensions.DependencyInjection;

/// <summary>Extension methods for setting up IceRpc.Slice services in an <see cref="IServiceCollection" />.</summary>
public static class IceRpcSliceServiceCollectionExtensions
{
    /// <summary>Adds a singleton for interface <typeparamref name="T"/>. The implementation is a proxy generated by
    /// the Slice compiler.</summary>
    /// <typeparam name="T">The interface generated by the Slice compiler that the proxy implements.</typeparam>
    /// <typeparam name="TProxy">The proxy struct that implements <typeparamref name="T"/>.</typeparam>
    /// <param name="services">The service collection to add services to.</param>
    /// <param name="serviceAddress">The service address of the proxy; null is equivalent to the the default service
    /// address for the proxy type.</param>
    /// <returns>The service collection.</returns>
    public static IServiceCollection AddIceRpcProxy<T, TProxy>(
        this IServiceCollection services,
        ServiceAddress? serviceAddress = null)
        where T : class
        where TProxy : IProxy, T, new() =>
        services
            .AddSingleton<T>(provider =>
                serviceAddress is null ?
                new TProxy
                {
                    // SliceEncodeOptions is not an IOption-compatible class (and can't be): that's why we look it up
                    // directly.
                    EncodeOptions = provider.GetService<SliceEncodeOptions>(),
                    Invoker = provider.GetRequiredService<IInvoker>()
                }
                :
                new TProxy
                {
                    EncodeOptions = provider.GetService<SliceEncodeOptions>(),
                    Invoker = provider.GetRequiredService<IInvoker>(),
                    ServiceAddress = serviceAddress
                });

    /// <summary>Adds a singleton for interface <typeparamref name="T"/>. The implementation is a proxy generated by
    /// the Slice compiler.</summary>
    /// <typeparam name="T">The interface generated by the Slice compiler that the proxy implements.</typeparam>
    /// <typeparam name="TProxy">The proxy struct that implements <typeparamref name="T"/>.</typeparam>
    /// <param name="services">The service collection to add services to.</param>
    /// <param name="serviceAddressUri">The service address of the proxy as a URI.</param>
    /// <returns>The service collection.</returns>
    public static IServiceCollection AddIceRpcProxy<T, TProxy>(
        this IServiceCollection services,
        Uri serviceAddressUri)
        where T : class
        where TProxy : IProxy, T, new() =>
        services.AddIceRpcProxy<T, TProxy>(new ServiceAddress(serviceAddressUri));
}
