// Copyright (c) ZeroC, Inc.

using System.Collections.Immutable;
using System.IO.Pipelines;
using System.Reflection;
using ZeroC.CodeBuilder;
using ZeroC.Slice.Symbols;

namespace ZeroC.Slice.Generator;

/// <summary>Shared pipeline for Slice code generators.</summary>
internal static class GeneratorDriver
{
    /// <summary>Runs the generator pipeline: reads stdin, decodes symbols, generates code, writes stdout.</summary>
    /// <param name="generateCode">Maps an <see cref="ISymbol"/> to an optional <see cref="CodeBlock"/>. Return
    /// null for symbols this generator does not handle.</param>
    /// <param name="mapOutputPath">Maps a Slice file path to the generated output file path.</param>
    /// <param name="usings">The using directives to include in the preamble of each generated file.</param>
    internal static async Task RunAsync(
        Func<ISymbol, string, CodeBlock?> generateCode,
        Func<string, string> mapOutputPath,
        IList<string> usings)
    {
        using Stream stdin = Console.OpenStandardInput();
        var reader = PipeReader.Create(stdin);

        using Stream stdout = Console.OpenStandardOutput();
        var writer = PipeWriter.Create(stdout);

        await Symbols.Generator.RunAsync(reader, writer, RunCore).ConfigureAwait(false);

        GeneratorResponse RunCore(ImmutableList<SliceFile> symbolFiles)
        {
            // Validate CS attributes before generation.
            //
            // List<Diagnostic> diagnostics = CsAttributeValidator.Validate(symbolFiles);
            // TODO: enable validation once slicec correctly handles the diagnostics reported by the
            // generators.
            var diagnostics = new List<Diagnostic>();

            // Use the informational version (e.g., "0.6.0-preview.1") which is the semver string from
            // the <Version> MSBuild property. Fall back to the assembly version (e.g., "0.6.0.0") if
            // the informational version attribute is not present.
            Assembly assembly = Assembly.GetEntryAssembly()!;
            string generatorName = assembly.GetName().Name ?? "unknown";
            string version =
                CustomAttributeExtensions.GetCustomAttribute<AssemblyInformationalVersionAttribute>(
                    assembly)?.InformationalVersion
                ?? assembly.GetName().Version?.ToString()
                ?? "unknown";

            // Check for duplicate file basenames — two files with the same basename would produce the
            // same output file, with the second silently overwriting the first.
            var seenBasenames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (SliceFile file in symbolFiles)
            {
                string basename = Path.GetFileName(file.Path);
                if (seenBasenames.TryGetValue(basename, out string? previousPath))
                {
                    diagnostics.Add(new Diagnostic
                    {
                        Level = DiagnosticLevel.Error,
                        Message =
                            $"Multiple source files have the same filename '{basename}': " +
                            $"'{previousPath}' and '{file.Path}'. " +
                            "Generated files are written to a common directory, so source files must have unique filenames.",
                    });
                }
                else
                {
                    seenBasenames[basename] = file.Path;
                }
            }

            // Generate code for each source file, skipping generation if there are validation errors.
            var generatedFiles = new List<GeneratedFile>();
            if (!diagnostics.Any(d => d.Level == DiagnosticLevel.Error))
            {
                foreach (SliceFile file in symbolFiles)
                {
                    string currentNamespace = file.Module.Namespace;
                    var codeBlocks = new List<CodeBlock>();
                    foreach (ISymbol symbol in file.Contents)
                    {
                        if (generateCode(symbol, currentNamespace) is CodeBlock code)
                        {
                            codeBlocks.Add(code);
                        }
                    }

                    string fileName = Path.GetFileName(file.Path);

                    string usingDirectives = string.Join("\n", usings.Select(u => $"using {u};"));

                    string preamble = $$"""
                        // <auto-generated/>
                        // {{generatorName}} version: '{{version}}'
                        // Generated from file: '{{fileName}}'

                        #nullable enable

                        #pragma warning disable CS1591 // Missing XML Comment
                        #pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
                        #pragma warning disable CS0612 // Type or member is obsolete
                        #pragma warning disable CS0618 // Type or member is obsolete
                        #pragma warning disable CS0619 // Type or member is obsolete

                        {{usingDirectives}}

                        namespace {{currentNamespace}};

                        """;

                    var fileCode = new CodeBlock(preamble);
                    if (codeBlocks.Count > 0)
                    {
                        fileCode.AddBlock(CodeBlock.FromBlocks(codeBlocks));
                    }
                    generatedFiles.Add(new GeneratedFile
                    {
                        Path = mapOutputPath(file.Path),
                        Contents = fileCode.ToString() + "\n",
                    });
                }
            }

            return new GeneratorResponse
            {
                GeneratedFiles = generatedFiles,
                Diagnostics = diagnostics,
            };
        }
    }
}
