// Copyright (c) ZeroC, Inc.

using System.Collections.Immutable;
using System.IO.Pipelines;
using ZeroC.CodeBuilder;
using ZeroC.Slice.Codec;
using ZeroC.Slice.Generator;
using ZeroC.Slice.Symbols;
using System.Reflection;

using Compiler = ZeroC.Slice.Symbols.Compiler;

// The Slice compiler executes this program and writes the Slice2-encoded request to stdin.

using Stream stdin = Console.OpenStandardInput();
var reader = PipeReader.Create(stdin);

// Read until the Slice compiler closes stdin.
ReadResult readResult;
do
{
    readResult = await reader.ReadAsync().ConfigureAwait(false);
    if (!readResult.IsCompleted)
    {
        reader.AdvanceTo(readResult.Buffer.Start, readResult.Buffer.End);
    }
}
while (!readResult.IsCompleted);

var decoder = new SliceDecoder(
    readResult.Buffer,
    maxCollectionAllocation: (int)readResult.Buffer.Length * 16);
string op = decoder.DecodeString();

// Decode source files and reference files.
Compiler.SliceFile[] sourceFiles = decoder.DecodeSequence((ref decoder) => new Compiler.SliceFile(ref decoder));
Compiler.SliceFile[] referenceFiles = decoder.DecodeSequence((ref decoder) => new Compiler.SliceFile(ref decoder));

reader.AdvanceTo(readResult.Buffer.End);
reader.Complete();

// Convert decoded types into rich symbols with resolved references.
ImmutableList<SliceFile> symbolFiles = SymbolConverter.ConvertFiles(sourceFiles, referenceFiles);

// Validate CS attributes before generation.
var diagnostics = CsAttributeValidator.Validate(symbolFiles);

// Generate code for each source file, skipping generation if there are validation errors.
var generatedFiles = new List<Compiler.GeneratedFile>();
if (!diagnostics.Any(d => d.Level == Compiler.DiagnosticLevel.Error))
{
    foreach (SliceFile file in symbolFiles)
    {
        var codeBlocks = new List<CodeBlock>();
        foreach (ISymbol symbol in file.Contents)
        {
            CodeBlock? code = symbol switch
            {
                Struct s => StructGenerator.Generate(s),
                EnumWithUnderlying e => EnumWithUnderlyingGenerator.Generate(e),
                EnumWithFields e => EnumWithFieldsGenerator.Generate(e),
                _ => null,
            };

            if (code is not null)
            {
                codeBlocks.Add(code);
            }
        }

        if (codeBlocks.Count > 0)
        {
            string fileName = Path.GetFileName(file.Path);
            string csNamespace = file.Module.Namespace;

            // Use the informational version (e.g., "0.6.0-preview.1") which is the semver string from
            // the <Version> MSBuild property. Fall back to the assembly version (e.g., "0.6.0.0") if
            // the informational version attribute is not present.
            Assembly assembly = Assembly.GetEntryAssembly()!;
            string version =
                CustomAttributeExtensions.GetCustomAttribute<AssemblyInformationalVersionAttribute>(
                    assembly)?.InformationalVersion
                ?? assembly.GetName().Version?.ToString()
                ?? "unknown";

            string preamble = $$"""
                // <auto-generated/>
                // ZeroC.Slice.Generator version: '{{version}}'
                // Generated from file: '{{fileName}}'

                #nullable enable

                #pragma warning disable CS1591 // Missing XML Comment
                #pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
                #pragma warning disable CS0612 // Type or member is obsolete
                #pragma warning disable CS0618 // Type or member is obsolete
                #pragma warning disable CS0619 // Type or member is obsolete

                using ZeroC.Slice.Codec;

                [assembly:Slice("{{fileName}}")]

                namespace {{csNamespace}};
                """;

            var fileCode = new CodeBlock(preamble + "\n");
            fileCode.AddBlock(CodeBlock.FromBlocks(codeBlocks));
            generatedFiles.Add(new Compiler.GeneratedFile(
                Path.ChangeExtension(file.Path, ".slice"), fileCode.ToString()));
        }
    }
}

// Encode and write the response to stdout.
var pipe = new Pipe();
var encoder = new SliceEncoder(pipe.Writer);
encoder.EncodeSequence(
    generatedFiles,
    (ref encoder, file) =>
    {
        encoder.EncodeString(file.Path);
        encoder.EncodeString(file.Contents);
    });

encoder.EncodeSequence(
    diagnostics,
    (ref encoder, diagnostic) => diagnostic.Encode(ref encoder));

await pipe.Writer.FlushAsync().ConfigureAwait(false);
pipe.Writer.Complete();

using Stream stdout = Console.OpenStandardOutput();
await pipe.Reader.CopyToAsync(stdout).ConfigureAwait(false);
pipe.Reader.Complete();
