name: Run Tests

on:
  workflow_call:

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: 🧪 Test Slice Compiler
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path tools/slicec-cs/Cargo.toml
    - name: 🧪 Test
      run: dotnet test --no-build --verbosity normal
