name: Test Templates

runs:
  using: "composite"
  steps:
  - name: 🔗 Install Templates
    run: |
      dotnet new install src/IceRpc.Templates/bin/Debug/IceRpc.Templates.*.nupkg
    shell: bash
  - name: 🧪 Test IceRpc Slice Client Template
    run: mkdir -p templates-test/client && cd templates-test/client && dotnet new icerpc-slice-client && dotnet build
    shell: bash
  - name: 🧪 Test IceRpc Slice Server Template
    run: mkdir -p templates-test/server && cd templates-test/server && dotnet new icerpc-slice-server && dotnet build
    shell: bash
  - name: 🧪 Test IceRpc Slice DI Client Template
    run: mkdir -p templates-test/di-client && cd templates-test/di-client && dotnet new icerpc-slice-di-client && dotnet build
    shell: bash
  - name: 🧪 Test IceRpc Slice DI Server Template
    run: mkdir -p templates-test/di-server && cd templates-test/di-server && dotnet new icerpc-slice-di-server && dotnet build
    shell: bash
