name: Test Templates
description: "Tests the IceRPC project templates"

runs:
  using: "composite"
  steps:

  # Protobuf Client template
  - name: 🧪 Test IceRpc + Protobuf Client Template
    run: |
      dotnet new icerpc-protobuf-client -o templates-test/tcp/ProtobufClient
      dotnet build templates-test/tcp/ProtobufClient/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  - name: 🧪 Test IceRpc + Protobuf Client Template with Quic
    run: |
      dotnet new icerpc-protobuf-client -o templates-test/quic/ProtobufClient --transport quic
      dotnet build templates-test/quic/ProtobufClient/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  # Protobuf Server template

  - name: 🧪 Test IceRpc + Protobuf Server Template
    run: |
      dotnet new icerpc-protobuf-server -o templates-test/tcp/ProtobufServer
      dotnet build templates-test/tcp/ProtobufServer/ /p:TreatWarningsAsErrors=true
    shell: pwsh
  
  - name: 🧪 Test IceRpc + Protobuf Server Template with Quic
    run: |
      dotnet new icerpc-protobuf-server -o templates-test/quic/ProtobufServer --transport quic
      dotnet build templates-test/quic/ProtobufServer/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  # Slice Client template

  - name: 🧪 Test IceRpc + Slice Client Template
    run: |
      dotnet new icerpc-slice-client -o templates-test/tcp/SliceClient
      dotnet build templates-test/tcp/SliceClient/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  - name: 🧪 Test IceRpc + Slice Client Template with Quic
    run: |
      dotnet new icerpc-slice-client -o templates-test/quic/SliceClient --transport quic
      dotnet build templates-test/quic/SliceClient/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  # Slice Server template

  - name: 🧪 Test IceRpc + Slice Server Template
    run: |
      dotnet new icerpc-slice-server -o templates-test/tcp/SliceServer
      dotnet build templates-test/tcp/SliceServer/ /p:TreatWarningsAsErrors=true
    shell: pwsh
  
  - name: 🧪 Test IceRpc + Slice Server Template with Quic
    run: |
      dotnet new icerpc-slice-server -o templates-test/quic/SliceServer --transport quic
      dotnet build templates-test/quic/SliceServer/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  # Protobuf DI Client template

  - name: 🧪 Test IceRpc + Protobuf DI Client Template
    run: |
      dotnet new icerpc-protobuf-di-client -o templates-test/ProtobufDIClient
      dotnet build templates-test/ProtobufDIClient/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  # Protobuf DI Server template

  - name: 🧪 Test IceRpc + Protobuf DI Server Template
    run: |
      dotnet new icerpc-protobuf-di-server -o templates-test/ProtobufDIServer
      dotnet build templates-test/ProtobufDIServer/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  # Slice DI Client template

  - name: 🧪 Test IceRpc + Slice DI Client Template
    run: |
      dotnet new icerpc-slice-di-client -o templates-test/SliceDIClient
      dotnet build templates-test/SliceDIClient/ /p:TreatWarningsAsErrors=true
    shell: pwsh

  # Slice DI Server template

  - name: 🧪 Test IceRpc + Slice DI Server Template
    run: |
      dotnet new icerpc-slice-di-server -o templates-test/SliceDIServer
      dotnet build templates-test/SliceDIServer/ /p:TreatWarningsAsErrors=true
    shell: pwsh
