name: Test Templates

runs:
  using: "composite"
  steps:
  - name: 🔗 Install Templates
    run: |
      ./build.sh push
      ./build.sh install-templates
    shell: bash
  - name: 🧪 Test IceRpc Client Template
    run: mkdir -p templates-test/client && cd templates-test/client && dotnet new icerpc-client && dotnet build
    shell: bash
  - name: 🧪 Test IceRpc Server Template
    run: mkdir -p templates-test/server && cd templates-test/server && dotnet new icerpc-server && dotnet build
    shell: bash
