name: Build Dist

inputs:
  cargo-build-args:
    description: 'Cargo Build Args'
    required: false
    default: ''
  target:
    description: 'The target platform'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
  - name: 📦 Cargo Cache
    uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        tools/slicec-cs/target/
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      restore-keys: |
        ${{ runner.os }}-cargo-
  - name: 🔗 Start SSH Agent
    uses: webfactory/ssh-agent@v0.5.4
    with:
      ssh-private-key: ${{ env.ICERPC_DEPLOY_KEY }}
  - name: Toolchain
    uses: dtolnay/rust-toolchain@stable
    with:
      toolchain: stable
      targets: ${{ inputs.target }}
  - name: Build Slice Compiler
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    run: |
      cargo build --manifest-path tools/slicec-cs/Cargo.toml ${{ inputs.cargo-build-args }} --target ${{ inputs.target }}
    shell: bash
