// Copyright (c) ZeroC, Inc. All rights reserved.

namespace IceRpc.Slice;

/// <summary>Provides default message for class DispatchException generated by the Slice compiler.</summary>
public partial class DispatchException
{
    /// <inheritdoc/>
    protected override string? DefaultMessage
    {
        get
        {
            string message = $"{nameof(DispatchException)} {{ ErrorCode = {ErrorCode} }}";

            if (Origin is OutgoingRequest request)
            {
                message += $" thrown by operation '{request.Operation}' on '{request.Proxy}'";
            }
            if (InnerException is not null)
            {
#if DEBUG
                message += $":\n{InnerException}\n---";
#else
                // The stack trace of the inner exception can include sensitive information we don't want to
                // send "over the wire" in non-debug builds.
                message += $":\n{InnerException.Message}";
#endif
            }
            return message;
        }
    }
}
