// Copyright (c) ZeroC, Inc. All rights reserved.

namespace IceRpc.Slice
{
    // Extends partial class DispatchException generated by the Slice compiler.
    public partial class DispatchException
    {
        /// <inheritdoc/>
        protected override string? DefaultMessage
        {
            get
            {
                string message = $"{nameof(DispatchException)} {{ ErrorCode = {ErrorCode} }}";

                if (Origin is IncomingResponse response)
                {
                    message += $" thrown by operation '{response.Request.Operation}' on '{response.Request.Proxy}'";
                }
                if (InnerException != null)
                {
#if DEBUG
                    message += $":\n{InnerException}\n---";
#else
                    // The stack trace of the inner exception can include sensitive information we don't want to
                    // send "over the wire" in non-debug builds.
                    message += $":\n{InnerException.Message}";
#endif
                }
                return message;
            }
        }
    }
}
