// Copyright (c) ZeroC, Inc.

using System.ComponentModel;

namespace IceRpc.Slice;

/// <summary>Marks helper methods generated by the Slice compiler on Service interfaces from Slice operations. This
/// attribute is used by <see cref="Service.DispatchAsync" />.</summary>
[AttributeUsage(AttributeTargets.Method, Inherited = false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class SliceOperationAttribute : Attribute
{
    /// <summary>Gets the operation name.</summary>
    /// <value>The operation name.</value>
    public string Value { get; }

    /// <summary>Constructs a Slice operation attribute.</summary>
    /// <param name="value">The operation name.</param>>
    public SliceOperationAttribute(string value) => Value = value;
}
