// Copyright (c) ZeroC, Inc. All rights reserved.

namespace IceRpc.Slice
{
    /// <summary>Provides default message for class DispatchException generated by the Slice compiler.</summary>
    public partial class UnknownException
    {
        /// <inheritdoc/>
        protected override string? DefaultMessage =>
            $"{nameof(UnknownException)} {{ TypeId = {TypeId}, Message = {SliceMessage} }}";
    }
}
