name: 'Check spelling'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          files: |
            **/*.{md,slice}
