name: Lint

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: "npm"
    - name: Install dependencies
      run: npm install prettier @prettier/plugin-xml
      shell: bash
    - name: Lint XML
      run: npx prettier --check '**/*.{props,csproj,targets}' --plugin=@prettier/plugin-xml
      shell: bash
