// Copyright (c) ZeroC, Inc.

using Google.Protobuf;
using Google.Protobuf.Compiler;
using Google.Protobuf.Reflection;
using IceRpc.Protoc;
using System.Text;

using Stream stdin = Console.OpenStandardInput();
var request = new CodeGeneratorRequest();
request.MergeFrom(stdin);

var sources = new List<ByteString>();
foreach (FileDescriptorProto? proto in request.ProtoFile)
{
    sources.Add(proto.ToByteString());
}
IReadOnlyList<FileDescriptor> descriptors = FileDescriptor.BuildFromByteStrings(sources);

var response = new CodeGeneratorResponse();
foreach (FileDescriptor descriptor in descriptors)
{
    if (!request.FileToGenerate.Contains(descriptor.Name))
    {
        // This descriptor represents a reference file for which we are not generating code.
        continue;
    }

    var builder = new StringBuilder();
    string preamble = $@"
// <auto-generated/>
// protoc-gen-icerpc-csharp version: 0.2.0
// Generated from file: {descriptor.Name}

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment

using IceRpc.Protobuf;

namespace {descriptor.GetCsharpNamespace()};".Trim();
    builder.AppendLine(preamble);

    foreach (ServiceDescriptor service in descriptor.Services)
    {
        builder.Append(ClientGenerator.GenerateInterface(service));
        builder.Append(ClientGenerator.GenerateImplementation(service));
        builder.Append(ServiceGenerator.GenerateInterface(service));
    }

    response.File.Add(
        new CodeGeneratorResponse.Types.File
        {
            Name = Path.ChangeExtension(Path.GetFileName(descriptor.Name), ".IceRpc.cs"),
            Content = builder.ToString()
        });
}
using Stream stdout = Console.OpenStandardOutput();
response.WriteTo(stdout);
