// Copyright (c) ZeroC, Inc.

using IceRpc.Features;
using IceRpc.Slice;

namespace HelloExample;

/// <summary>A Chatbot is an IceRPC service that implements Slice interface 'Hello'. In C#, Chatbot is class that
/// derives from class <see cref="Service" /> and implements the interface <see cref="IHelloService" /> generated by the
/// Slice compiler.</summary>
internal class Chatbot : Service, IHelloService
{
    public ValueTask<string> SayHelloAsync(
        string name,
        IFeatureCollection features,
        CancellationToken cancellationToken)
    {
        Console.WriteLine($"Dispatching sayHello request {{ name = '{name}' }}");
        return new($"Hello, {name}!");
    }
}
