// Copyright (c) ZeroC, Inc.

using IceRpc;
using IceRpc.Transports.Slic;
using IceRpc.Transports.Tcp;
using VisitorCenter;

// Create a connection that uses the TCP client transport.
// Since TcpClientTransport is a duplex transport, we wrap it in a SlicClientTransport to get a multiplexed transport.
await using var connection = new ClientConnection(
    new Uri("icerpc://localhost"),
    multiplexedClientTransport: new SlicClientTransport(new TcpClientTransport()));

// GreeterClient is a struct generated by protoc-gen-icerpc-csharp.
var greeter = new GreeterClient(connection);

var request = new GreetRequest { Name = Environment.UserName };
GreetResponse response = await greeter.GreetAsync(request);

Console.WriteLine(response.Greeting);

await connection.ShutdownAsync();
