// Copyright (c) ZeroC, Inc.

using IceRpc;
using VisitorCenter;

// Create a connection that uses the TCP client transport instead of the default, QUIC.
await using var connection = new ClientConnection(new Uri("icerpc://localhost?transport=tcp"));

// GreeterClient is a struct generated by protoc-gen-icerpc-csharp.
var greeter = new GreeterClient(connection);

var request = new GreetRequest { Name = Environment.UserName };
GreetResponse response = await greeter.GreetAsync(request);

Console.WriteLine(response.Greeting);

await connection.ShutdownAsync();
