// Copyright (c) ZeroC, Inc. All rights reserved.

namespace IceRpc
{
    /// <summary>All mapped structs generated by the Slice compiler implement IEncodableStruct.</summary>
    public interface IEncodableStruct
    {
        /// <summary>Writes this instance to the buffer.</summary>
        /// <param name="writer">The buffer writer.</param>
        void IceWrite(BufferWriter writer);
    }
}
