name: Build Examples

runs:
  using: "composite"
  steps:
  - name: 🔨 Build Examples
    run: |
      for solution in examples/*/*.sln examples/*/*/*.sln; donet build "$solution"; done
      dotnet build docfx/examples/Examples.sln
    shell: bash
