// Copyright (c) ZeroC, Inc.

using IceRpc;

// Slice module VisitorCenter in Greeter.slice maps to C# namespace VisitorCenter.
using VisitorCenter;

await using var connection = new ClientConnection(new Uri("icerpc://localhost"));

// GreeterProxy is a struct generated by the Slice compiler.
var greeterProxy = new GreeterProxy(connection);

string greeting = await greeterProxy.GreetAsync(Environment.UserName);

Console.WriteLine(greeting);

await connection.ShutdownAsync();
