name: "Build .NET Packages"

on:
  workflow_call:
    inputs:
      icerpc_version:
        required: false
        type: string
      channel:
        required: true
        type: string
      authenticode_sign:
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      icerpc_version:
        description: "The IceRPC version to build"
        required: false
      channel:
        description: "Release channel (e.g., stable, nightly)"
        required: true
        default: "nightly"
      authenticode_sign:
        description: "Sign the assemblies with authenticode"
        required: false
        type: boolean
        default: false

jobs:
  build-packages:
    runs-on: windows-2025
    timeout-minutes: 10
    env:
      VERSION: ${{ inputs.icerpc_version }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Build IceRPC
        run: dotnet build --configuration Release

      - name: Collect Files to Sign
        if: inputs.authenticode_sign
        run: |
            # For each project in src, we sign the main assembly named after the project.
            $assemblies = Get-ChildItem -Path src -Directory | ForEach-Object {
              $name = $_.Name
              Get-ChildItem -Path $_.FullName -Filter "$name.dll" -Recurse |
              Where-Object { $_.FullName -like "*\bin\Release\net*\$name.dll" } |
              ForEach-Object { Resolve-Path -Relative $_.FullName }
            }
            $assemblies | Set-Content -Path "${{ github.workspace }}\catalog.txt" -Encoding UTF8

      # Shutdown the build server before signing to ensure MSBuild tasks are not loaded in the build server process.
      - name: Shutdown build server
        if: inputs.authenticode_sign
        run: dotnet build-server shutdown

      - name: Sign .NET Assemblies
        if: inputs.authenticode_sign
        uses: azure/trusted-signing-action@v1
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://eus.codesigning.azure.net/
          trusted-signing-account-name: zeroc
          certificate-profile-name: zeroc-ice
          files-catalog: ${{ github.workspace }}\catalog.txt
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      # Use --no-build to avoid rebuilding, we want to use the signed assemblies that were built in the previous step.
      - name: Pack IceRPC
        run: dotnet pack --no-build --configuration Release --output .

      - name: Update IceRPC Templates version
        run: |
          $oldVersion = '0.6.0-preview.1'
          $newVersion = '${{ env.VERSION }}'
          Get-ChildItem -Path 'src/IceRpc.Templates' -Recurse -Filter '*.csproj' |
            ForEach-Object {
              $path = $_.FullName
              Write-Host "Updating $path"
              (Get-Content $path -Raw) -replace [regex]::Escape($oldVersion), $newVersion | Set-Content $path
            }
        if: ${{ inputs.channel == 'nightly' }}

      - name: Pack IceRPC Templates
        working-directory: src/IceRpc.Templates
        run: dotnet pack --configuration Release --output ../../

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v6
        with:
          name: nuget-packages
          path: |
            ./*.nupkg
            ./*.snupkg
