name: SliceC Compiler Release Build

on:
  workflow_call:
    inputs:
      target-os:
        required: true
        type: string
    secrets:
      ICERPC_DEPLOY_KEY:
        required: true

jobs:
  build-compilers:
    runs-on: ${{ inputs.target-os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/build-compiler
      with:
        cargo-build-args: --release
        dotnet-build-args: --configuration Release
      env:
        ICERPC_DEPLOY_KEY: ${{ secrets.ICERPC_DEPLOY_KEY }}
