name: SliceC Compiler Release Build

on:
  workflow_call:
    inputs:
      target-os:
        required: true
        type: string
      compiler-exe:
        required: false
        default: slicec-cs
        type: string
    secrets:
      ICERPC_DEPLOY_KEY:
        required: true

jobs:
  build-compilers:
    runs-on: ${{ inputs.target-os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/build-compiler
      with:
        cargo-build-args: --release
      env:
        ICERPC_DEPLOY_KEY: ${{ secrets.ICERPC_DEPLOY_KEY }}
    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.compiler-exe }}-${{ inputs.target-os }}
        path: tools/slicec-cs/target/release/${{ inputs.compiler-exe }}
