name: release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


env:
  SignTool: C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64\signtool.exe

jobs:
  build-packages:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Create Code Signing Certificate
        run: |
          mkdir C:\tmp\certificates
          Set-Content -Path C:\tmp\certificates\certificate.pfx.base64 -Value '${{ secrets.CERTIFICATE }}'
          certutil -decode C:\tmp\certificates\certificate.pfx.base64 C:\tmp\certificates\certificate.pfx
          Remove-Item C:\tmp\certificates\certificate.pfx.base64
      - name: Build
        run: dotnet build
        working-directory: tools\IceRpc.Slice.Tools
        env:
          SLICEC_DEPLOY_KEY: ${{ secrets.SLICEC_DEPLOY_KEY }}
          SIGN_CERTIFICATE: C:\tmp\certificates\certificate.pfx
          SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
      - name: Cleanup
        if: always()
        run: Remove-Item C:\tmp\certificates\certificate.pfx -ErrorAction SilentlyContinue
      - name: Pack IceRPC
        run: dotnet pack --configuration Release --output .
