name: "Publish NuGet Packages"

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "The channel to publish to (e.g., stable, nightly)"
        required: true
      run_id:
        description: "The run ID to use for downloading artifacts"
        required: true
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      run_id:
        required: true
        type: string

jobs:
  build:
    name: "Publish NuGet Packages"
    runs-on: ubuntu-24.04

    steps:
      - name: Download NuGet artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ inputs.run_id }}
        run: |
          set -euo pipefail
          mkdir -p staging
          gh run download "$RUN_ID" --repo icerpc/icerpc-csharp --name "nuget-packages" --dir staging

      - name: Publish NuGet Packages
        run: |
          set -euo pipefail

          NUGET_ORG_URL="https://api.nuget.org/v3/index.json"
          NEXUS_NIGHTLY_URL="https://download.zeroc.com/nexus/repository/nuget-nightly/"

          # Collect all packages. The symbol package ".snupkg" files are published automatically with the main
          # package, no need to push them separately.
          mapfile -t packages < <(find staging -type f -name "*.nupkg")

          for package in "${packages[@]}"; do
            echo "Publishing package: $package"
            name=$(basename "$package")

            case "$CHANNEL" in
              "stable")
                # ZeroC-prefixed packages belong to the ZeroC NuGet.org organization;
                # IceRpc-prefixed packages belong to the IceRPC NuGet.org organization.
                if [[ "$name" == ZeroC.* ]]; then
                  dotnet nuget push "$package" --source "$NUGET_ORG_URL" --api-key "$ZEROC_NUGET_API_KEY"
                else
                  dotnet nuget push "$package" --source "$NUGET_ORG_URL" --api-key "$ICERPC_NUGET_API_KEY"
                fi
                ;;
              "nightly")
                dotnet nuget push "$package" --source "$NEXUS_NIGHTLY_URL" --api-key "$NEXUS_NIGHTLY_NUGET_API_KEY"
                ;;
              *)
                echo "Unsupported channel: $CHANNEL"
                exit 1
                ;;
            esac
          done
        env:
          CHANNEL: ${{ inputs.channel }}
          NEXUS_NIGHTLY_NUGET_API_KEY: ${{ secrets.NEXUS_NIGHTLY_NUGET_API_KEY }}
          ZEROC_NUGET_API_KEY: ${{ secrets.ZEROC_NUGET_API_KEY }}
          ICERPC_NUGET_API_KEY: ${{ secrets.ICERPC_NUGET_API_KEY }}
