name: slicec-cs Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - name: 📦 Cargo Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          tools/slicec-cs/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: 🔨 Build
      run: cargo build --all --all-features --manifest-path tools/slicec-cs/Cargo.toml
    - name: 🧪 Test
      run: cargo test --manifest-path tools/slicec-cs/Cargo.toml
    - name: 🔎 Lint
      run: cargo clippy --all-features --no-deps --all-targets --manifest-path tools/slicec-cs/Cargo.toml

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: 📦 Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly
      - name: 🔎 Format using rustfmt
        run: cargo +nightly fmt --check --manifest-path tools/slicec-cs/Cargo.toml
