name: "Check spelling"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  spellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: streetsidesoftware/cspell-action@6f3c77c1406bc930f944ba97e9801a22e42caf58 # v9.1.0
        with:
          files: |
            **/*.{cs,rs,md,json,csproj,slice}
